import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Circle, Download, Flag, Pause, Play, RefreshCw, Save, ScanLine, SkipBack, SkipForward, Square, Trash2, Upload } from 'lucide-react';
import { Euler, Quaternion } from 'three';
import type { CubeRecording } from '../../../../packages/cube-lab/src/recording.js';
import { cubeLab, useCubeLab } from './store.js';
import { deleteRecording, savedRecordings, saveRecording } from './recording-library.js';
import { downloadBlob } from '../planner/export.js';
import { confirmAction } from '../planner/dialogs.js';
import { workspace } from '../planner/store.js';
import './cube-lab.css';

async function replaceTake() { return !cubeLab.get().recording?.samples.length || await confirmAction('Replace this take?', 'Save or export the current recording before replacing it.'); }
async function action(task: () => void | Promise<void>) { try { await task(); } catch (error) { cubeLab.set({ message: error instanceof Error ? error.message : String(error) }); } }
const seconds = (ms: number) => `${(ms / 1000).toFixed(2)} s`;
export function CubeLeftPanel() {
  const s = useCubeLab(); const input = useRef<HTMLInputElement>(null); const [saved, setSaved] = useState<CubeRecording[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void savedRecordings().then(values => { if (active) setSaved(values); }).catch(() => { if (active) cubeLab.set({ message: 'Local recording storage unavailable. JSON export is still available.' }); }); return () => { active = false; }; }, []);
  const recording = s.mode === 'RECORDING'; const ready = s.enabled && !s.preview && (s.tracking === 'DETECTED' || s.tracking === 'TRACKING');
  return <aside className="furniture-panel cube-panel">
    <div className="panel-title">4D Cube Lab</div>
    <section className="property-section"><h3>Recording</h3><label className="text-field">Take name<input maxLength={80} value={s.name} onChange={e => cubeLab.set({ name: e.target.value })} /></label>
      <button className="primary" disabled={!ready || recording} onClick={() => void action(async () => { if (await replaceTake()) cubeLab.start(); })}><Circle size={15} />Start Recording</button>
      <div className="cube-button-row"><button disabled={!recording} onClick={() => cubeLab.pauseRecording()}>{s.paused ? <Play size={15} /> : <Pause size={15} />}{s.paused ? 'Resume' : 'Pause'}</button><button disabled={!recording} onClick={() => cubeLab.stop()}><Square size={14} />Stop</button></div>
      <button disabled={!s.recording} onClick={() => void action(async () => { if (await replaceTake()) cubeLab.clear(); })}><Trash2 size={14} />Clear</button>
      <dl><dt>Mode</dt><dd data-testid="cube-mode">{s.mode}{s.paused ? ' / PAUSED' : ''}</dd><dt>Samples</dt><dd data-testid="cube-samples">{s.recording?.samples.length ?? 0}</dd><dt>Duration</dt><dd>{seconds(recording ? s.time : s.recording?.durationMs ?? 0)}</dd></dl>
      <label className="numeric-field">Sample / vision Hz<input type="number" min={10} max={20} step={1} value={s.sampleRate} disabled={recording} onChange={e => { const n = e.target.valueAsNumber; if (Number.isInteger(n) && n >= 10 && n <= 20) cubeLab.set({ sampleRate: n }); }} /></label>
    </section>
    <section className="property-section"><h3>Recording Library</h3><button disabled={busy || recording || !s.recording?.samples.length} onClick={() => void action(async () => { setBusy(true); try { const r = cubeLab.get().recording!; const value = { ...r, name: s.name.trim() || r.name }; await saveRecording(value); cubeLab.set({ recording: value }); setSaved(await savedRecordings()); workspace.notify('Cube recording saved locally'); } finally { setBusy(false); } })}><Save size={15} />Save Recording</button>
      <div className="cube-button-row"><button disabled={!s.recording?.samples.length || recording} title="Export Recording JSON" aria-label="Export Recording JSON" onClick={() => { if (s.recording) downloadBlob(new Blob([JSON.stringify({ ...s.recording, name: s.name.trim() || s.recording.name }, null, 2)], { type: 'application/json' }), `cube-recording-${s.recording.createdAt.slice(0, 10)}.json`); }}><Download size={16} />JSON</button><button title="Import Recording JSON" aria-label="Import Recording JSON" onClick={() => input.current?.click()}><Upload size={16} />JSON</button></div>
      <input hidden ref={input} type="file" accept=".json,application/json" onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) void action(async () => { if (file.size > 8 * 1024 * 1024) throw new Error('Recording exceeds 8 MB'); const value: unknown = JSON.parse(await file.text()); if (await replaceTake()) cubeLab.load(value); }); }} />
      <div className="cube-library">{saved.map(r => <div className="saved-project-row" key={r.recordingId}><button onClick={() => void action(async () => { if (await replaceTake()) cubeLab.load(r); })}><strong>{r.name}</strong><small>{r.createdAt.slice(0, 10)} / {seconds(r.durationMs)} / {r.samples.length} samples</small></button><button title={`Delete ${r.name}`} aria-label={`Delete ${r.name}`} onClick={() => void action(async () => { if (await confirmAction('Delete saved recording?', r.name)) { await deleteRecording(r.recordingId); setSaved(await savedRecordings()); } })}><Trash2 size={14} /></button></div>)}</div>
    </section>
    <details className="cube-info"><summary>Why Is This 4D?</summary><p>X = horizontal position<br />Y = vertical position<br />Z = depth<br />T = time</p><p>Pose = P(x, y, z, rotation, t)</p><p>The cube occupies different positions and orientations as time changes. A recorded pose can be revisited and replayed.</p></details>
  </aside>;
}
export function CubeRightPanel() {
  const s = useCubeLab(); const pose = cubeLab.pose(); const rotation = pose ? new Euler().setFromQuaternion(new Quaternion(pose.rotation.x, pose.rotation.y, pose.rotation.z, pose.rotation.w), 'XYZ') : null;
  const number = (value?: number) => value === undefined ? '--' : value.toFixed(3);
  const locked = s.enabled || s.mode === 'RECORDING';
  return <aside className="properties-panel cube-panel">
    <div className="panel-title">Cube 01 / ID 101</div><div className={`tracking-state ${s.tracking === 'LOST' ? 'cube-lost' : ''}`} role="status" data-testid="cube-tracking">{s.tracking === 'LOST' ? 'TRACKING LOST' : s.tracking}</div>
    <section className="property-section"><h3>Approximate Pose</h3><dl className="cube-pose"><dt>X</dt><dd data-testid="cube-x">{number(pose?.position.x)} m</dd><dt>Y</dt><dd data-testid="cube-y">{number(pose?.position.y)} m</dd><dt>Z</dt><dd data-testid="cube-z">{number(pose?.position.z)} m</dd><dt>Distance</dt><dd>{number(pose ? Math.hypot(...Object.values(pose.position)) : undefined)} m</dd><dt>Pitch</dt><dd>{rotation ? (rotation.x * 180 / Math.PI).toFixed(1) : '--'} deg</dd><dt>Yaw</dt><dd>{rotation ? (rotation.y * 180 / Math.PI).toFixed(1) : '--'} deg</dd><dt>Roll</dt><dd>{rotation ? (rotation.z * 180 / Math.PI).toFixed(1) : '--'} deg</dd></dl>
      <button disabled={s.mode === 'RECORDING'} onClick={() => cubeLab.toggleTracking()}><ScanLine size={15} />{s.enabled ? 'Stop tracking' : 'Start tracking'}</button>
      <button disabled={s.mode === 'RECORDING'} onClick={() => cubeLab.live()}><RefreshCw size={15} />Return to Live</button>
    </section>
    <section className="property-section"><h3>Camera Calibration</h3>
      <label className="numeric-field">Marker size (mm)<input disabled={locked} type="number" min={5} max={500} value={s.markerSizeMm} onChange={e => { const v = e.target.valueAsNumber; if (v >= 5 && v <= 500) cubeLab.set({ markerSizeMm: v }); }} /></label>
      <label className="numeric-field">Cube side (mm)<input disabled={locked} type="number" min={5} max={1000} value={s.cubeSizeMm} onChange={e => { const v = e.target.valueAsNumber; if (v >= 5 && v <= 1000) cubeLab.set({ cubeSizeMm: v }); }} /></label>
      <label className="text-field">FOV axis<select disabled={locked} value={s.fovAxis} onChange={e => cubeLab.set({ fovAxis: e.target.value as typeof s.fovAxis })}><option value="vertical">Vertical</option><option value="horizontal">Horizontal</option></select></label>
      <label className="numeric-field">FOV (degrees)<input disabled={locked} type="number" min={15} max={120} value={s.fov} onChange={e => { const v = e.target.valueAsNumber; if (v >= 15 && v <= 120) cubeLab.set({ fov: v }); }} /></label>
      <dl><dt>Resolution</dt><dd>{s.width} x {s.height}</dd><dt>Intrinsics</dt><dd>Approximate</dd></dl>
      <button disabled={s.mode === 'RECORDING'} onClick={() => { if (s.enabled) cubeLab.toggleTracking(); cubeLab.live(); }}><RefreshCw size={15} />Recalibrate Cube</button>
      <a className="marker-download" href="/markers/cube-marker-print.pdf" target="_blank" rel="noreferrer">Print cube marker / 40 mm</a>
    </section>
    <section className="property-section"><h3>Visualization</h3><label className="text-field">Smoothing<select value={s.smoothing} onChange={e => cubeLab.set({ smoothing: e.target.value as typeof s.smoothing })}>{['Off', 'Low', 'Medium', 'High'].map(v => <option key={v}>{v}</option>)}</select></label>
      {(['cube', 'trajectory', 'axes', 'label'] as const).map(key => <label className="check-field" key={key}><input type="checkbox" checked={s[key]} onChange={e => cubeLab.set({ [key]: e.target.checked })} />{{ cube: 'Virtual Cube', trajectory: 'Trajectory', axes: 'Axes', label: 'Coordinate Label' }[key]}</label>)}
      <label className="check-field"><input type="checkbox" disabled={s.enabled || s.mode === 'RECORDING'} checked={s.preview} onChange={e => { cubeLab.live(); cubeLab.set({ preview: e.target.checked }); }} />Test cube preview</label>
    </section>
    <details className="cube-info"><summary>Developer View</summary><label className="check-field"><input type="checkbox" checked={s.debug} onChange={e => cubeLab.set({ debug: e.target.checked })} />Marker corners / ID 101</label><dl><dt>Detection</dt><dd>{s.debugResult?.fps.toFixed(1) ?? '--'} Hz</dd><dt>POSIT error</dt><dd>{s.debugResult?.error?.toFixed(2) ?? '--'} px</dd></dl><pre>Raw: {JSON.stringify(s.raw, null, 2)}{ '\n' }Filtered: {JSON.stringify(s.filtered, null, 2)}</pre></details>
    {s.message && <p className="overlap-warning" role="alert">{s.message}</p>}
  </aside>;
}
export function CubeTimeline() {
  const s = useCubeLab(); const [keyName, setKeyName] = useState('Start'); const [page, setPage] = useState(0); const samples = s.recording?.samples ?? []; const end = s.mode === 'RECORDING' ? s.time : s.recording?.durationMs ?? 0;
  return <section className="timeline-panel cube-timeline" aria-label="Cube recording timeline"><div className="timeline-heading"><strong>Cube Timeline</strong><span>{s.mode}{s.paused ? ' / PAUSED' : ''}</span><output data-testid="cube-time">{seconds(s.time)} / {seconds(end)}</output><label>Speed<select value={s.speed} onChange={e => cubeLab.set({ speed: Number(e.target.value) })}>{[.25, .5, 1, 2].map(n => <option key={n} value={n}>{n}x</option>)}</select></label><label><input type="checkbox" checked={s.loop} onChange={e => cubeLab.set({ loop: e.target.checked })} />Loop</label></div>
    <div className="timeline-controls"><button aria-label="Cube first frame" title="First frame" disabled={!samples.length} onClick={() => cubeLab.seek(0)}><SkipBack size={16} /></button><button aria-label="Cube previous sample" title="Previous sample" disabled={!samples.length} onClick={() => cubeLab.step(-1)}><ChevronLeft size={16} /></button><button aria-label={s.playing ? 'Pause cube playback' : 'Play cube recording'} title={s.playing ? 'Pause playback' : 'Play recording'} disabled={!samples.length} onClick={() => { if (s.playing) cubeLab.set({ playing: false }); else cubeLab.play(); }}>{s.playing ? <Pause size={17} /> : <Play size={17} />}</button><button aria-label="Cube next sample" title="Next sample" disabled={!samples.length} onClick={() => cubeLab.step(1)}><ChevronRight size={16} /></button><button aria-label="Cube last frame" title="Last frame" disabled={!samples.length} onClick={() => cubeLab.seek(s.recording?.durationMs ?? 0)}><SkipForward size={16} /></button><div className="cube-time-track"><input aria-label="Cube time" type="range" min={0} max={Math.max(1, end)} step={1} value={s.time} disabled={!samples.length} onChange={e => cubeLab.seek(Number(e.target.value))} /><div className="cube-time-flags">{s.recording?.keyframes.map(k => <button key={k.id} title={`${k.name} / ${seconds(k.timestampMs)}`} aria-label={`Seek keyframe ${k.name}`} style={{ left: `${end ? k.timestampMs / end * 100 : 0}%` }} onClick={() => cubeLab.seek(k.timestampMs)}><Flag size={12} /></button>)}</div></div></div>
    <div className="cube-keyframes"><label>Keyframe name<input value={keyName} maxLength={60} onChange={e => setKeyName(e.target.value)} /></label><button disabled={!samples.length || !keyName.trim() || (s.recording?.keyframes.length ?? 0) >= 100} onClick={() => { cubeLab.addKeyframe(keyName); setKeyName(`State ${(s.recording?.keyframes.length ?? 0) + 1}`); }}><Flag size={14} />Add Keyframe</button>{s.recording?.keyframes.map(k => <button key={k.id} title={seconds(k.timestampMs)} onClick={() => cubeLab.seek(k.timestampMs)}><Flag size={12} />{k.name}<small>{seconds(k.timestampMs)}</small></button>)}</div>
    <details className="cube-data"><summary>4D Data / {samples.length} samples</summary><table><thead><tr>{['Time', 'X (m)', 'Y (m)', 'Z (m)'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{samples.slice(Math.min(page, Math.max(0, Math.ceil(samples.length / 10) - 1)) * 10, (Math.min(page, Math.max(0, Math.ceil(samples.length / 10) - 1)) + 1) * 10).map(p => <tr key={p.timestampMs}><td>{seconds(p.timestampMs)}</td><td>{p.position.x.toFixed(3)}</td><td>{p.position.y.toFixed(3)}</td><td>{p.position.z.toFixed(3)}</td></tr>)}</tbody></table><div className="cube-button-row"><button aria-label="Previous data page" title="Previous data page" disabled={!page} onClick={() => setPage(page - 1)}><ChevronLeft size={15} /></button><button aria-label="Next data page" title="Next data page" disabled={(page + 1) * 10 >= samples.length} onClick={() => setPage(page + 1)}><ChevronRight size={15} /></button></div></details>
  </section>;
}
