import { pairDistance,type ResearchAnalysis,type ResearchEvent } from './research.js';
import { validSpatial } from './research-metrics.js';
export function deriveTemporalEvents(data:ResearchAnalysis):ResearchEvent[]{
  const events:ResearchEvent[]=[],last=new Map<string,number>(),pairs=new Map<string,{time:number;distance:number;trend:number;since:number;spatial:boolean}>();
  const emit=(type:ResearchEvent['type'],time:number,subjects:number[],quality:number,value:number,windowSeconds:number,description:string,spatial=false)=>{const key=`${type}:${subjects.join('-')}`;if(time-(last.get(key)??-Infinity)<1)return;last.set(key,time);events.push({id:`${key}:${time.toFixed(3)}`,time,type,subjects,confidence:Math.min(.7,quality),label:description,evidence:{coordinateSystem:spatial?'relative scene':'image',value,windowSeconds,description}});};
  for(const track of data.tracks){emit('enter',track.firstSeen,[track.id],track.quality?.score??track.classConfidence,track.observations,0,'First observed; entry is a hypothesis');if(track.lastSeen<data.video.duration-1/data.settings.fps)emit('exit',track.lastSeen,[track.id],track.quality?.score??track.classConfidence,track.observations,0,'Last observed; exit, miss or occlusion cannot be distinguished');}
  for(const frame of data.frames){for(const subject of frame.subjects){if(subject.velocity&&(subject.kinematicQuality??0)>=.3){const speed=subject.velocity.speed;if(speed<.12*(data.refinement?.scale??1))emit('stationary',frame.time,[subject.id],subject.kinematicQuality!,speed,.4,'Low smoothed relative speed; camera motion can contribute',true);if(speed>3*(data.refinement?.scale??1))emit('rapid motion',frame.time,[subject.id],subject.kinematicQuality!,speed,.4,'High smoothed relative speed; not animal intent',true);}}
    for(let i=0;i<frame.subjects.length;i++)for(let j=i+1;j<frame.subjects.length;j++){const a=frame.subjects[i],b=frame.subjects[j],ids=[a.id,b.id].sort((x,y)=>x-y),key=ids.join('-'),spatial=validSpatial(a)&&validSpatial(b),distance=spatial?pairDistance(a,b).scene!:pairDistance(a,b).image,quality=Math.min(a.confidence,b.confidence,spatial?a.depthEstimate.confidence??0:1,spatial?b.depthEstimate.confidence??0:1),prior=pairs.get(key),dt=prior?frame.time-prior.time:0,rate=prior&&dt>0&&dt<=.65&&spatial===prior.spatial?(distance-prior.distance)/dt:null,threshold=spatial?.12*(data.refinement?.scale??1):.025,trend=rate===null?0:rate<-threshold?-1:rate>threshold?1:0,since=prior&&trend===prior.trend&&dt<=.65?prior.since:frame.time;
      if(rate!==null&&trend&&frame.time-since>=.35)emit(trend<0?'approach':'retreat',frame.time,ids,quality,rate,frame.time-since,`${trend<0?'Decreasing':'Increasing'} ${spatial?'estimated scene':'image'} separation over consecutive observations`,spatial);
      if(distance<(spatial?.6*(data.refinement?.scale??1):.12)&&prior&&dt<=.65)emit('close encounter',frame.time,ids,quality,distance,dt,'Geometric proximity; not verified physical contact',spatial);
      pairs.set(key,{time:frame.time,distance,trend,since,spatial});
    }
  }return events.sort((a,b)=>a.time-b.time);
}
