import { densityRange,gaussianDensity,scopedBins } from '../../../../packages/shared/src/research-visual.js';
import { spatialBounds,spatialContext } from '../../../../packages/shared/src/research-spatial.js';
import { research } from './store.js';
export function densityTexture(values:Float64Array,max:number,opacity:number){
  const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d')!,pixels=ctx.createImageData(32,32);
  for(let i=0;i<values.length;i++){const value=max?values[i]/max:0,t=Math.sqrt(value),j=i*4;pixels.data[j]=Math.round(49+190*t);pixels.data[j+1]=Math.round(123+47*t);pixels.data[j+2]=Math.round(145-51*t);pixels.data[j+3]=value>.0001?Math.round(255*opacity*t):0;}ctx.putImageData(pixels,0,0);return canvas;
}
export function currentDensity(time:number){const state=research.get(),data=state.analysis;if(!data)throw new Error('No analysis');const mode=spatialContext(data,time,research.spatial).mode,range=densityRange(data.video.duration,time,state.options.heatmapScope??'clip',state.options.temporalWindow||2,state.range),box=spatialBounds(data,mode),bins=scopedBins(data,mode,state.options.heatmap??'all',state.selected,state.comparison,range,box),density=gaussianDensity(bins,{low:.65,medium:1.2,high:2}[state.options.densitySmoothing??'medium']);return {data,mode,range,box,bins,density};}
export function exportDensity(time:number,kind:'heatmap'|'heatmap-csv'){
  const {data,mode,range,box,bins,density}=currentDensity(time);if(!bins.size)throw new Error('No observed occupancy in the selected scope');
  let blob:Blob|undefined;const save=(blob:Blob,extension:string)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='4DLiveSpace_heatmap.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  if(kind==='heatmap-csv'){const rows=['bin_x,bin_z,center_x,center_z,subject_seconds,range_start,range_end,projection,units'];for(const [key,value] of bins){const [x,z]=key.split(':').map(Number);rows.push([x,z,box.x+(x+.5)/32*box.w,box.z+(z+.5)/32*box.h,value,range.start,range.end,mode,mode==='image'?'normalized image':data.refinement?.units??'relative scene units'].join(','));}blob=new Blob([rows.join('\r\n')],{type:'text/csv'});save(blob,'csv');return;}
  const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=900;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#111318';ctx.fillRect(0,0,1200,900);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.save();if(mode==='image')ctx.drawImage(densityTexture(density.values,density.max,.85),60,80,1080,700);else{ctx.translate(60,780);ctx.scale(1,-1);ctx.drawImage(densityTexture(density.values,density.max,.85),0,0,1080,700);}ctx.restore();ctx.fillStyle='#dbe4eb';ctx.font='20px sans-serif';ctx.fillText('4D LiveSpace / Smoothed Observed Occupancy / '+mode,30,36);ctx.font='16px sans-serif';ctx.fillText('T '+range.start.toFixed(2)+' - '+range.end.toFixed(2)+' s / '+density.total.toFixed(2)+' sampled subject-seconds / display smoothing, not probability',30,830);ctx.fillText('Low density - high density / raw aggregated bins available as CSV / Depth and scale are estimates',30,865);canvas.toBlob(blob=>{if(blob)save(blob,'png');},'image/png');
}
