import { researchFrameAt,trackColor as trackColorForExport,type ResearchAnalysis } from '../../../../packages/shared/src/research.js';
import { closestPairs,pairObservations } from '../../../../packages/shared/src/research-metrics.js';
import { spatialContext } from '../../../../packages/shared/src/research-spatial.js';
import { MotionProjectionService } from '../motion/MotionProjectionService.js';
import { drawResearchOverlay } from './VideoOverlayRenderer2D.js';
import { research,type ResearchOptions } from './store.js';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csv=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;
export function exportResearchData(data:ResearchAnalysis,kind:'report'|'frames'|'tracks'|'events'|'pairs'|'markdown'){
  if(kind==='markdown'){const pairs=closestPairs(data),text=['# 4D LiveSpace Analysis Report','','## Source',data.video.name,'','## Pipeline',data.pipelineVersion,...Object.entries(data.models).map(([name,model])=>`${name}: ${model.id} / ${model.revision}`),'','## Coordinate Scale',data.refinement?.units??'relative scene units','Smoothing: '+(data.refinement?.smoothing??'off'),'','## Tracked Subjects','| Track | Class hypothesis | Observations | Quality index |','| --- | --- | --- | --- |',...data.tracks.map(t=>`| ${t.id} | ${t.label} | ${t.observations} | ${t.quality?.score.toFixed(3)??'unavailable'} |`),'','## Closest Approaches','| Pair | Image T / separation | Scene T / estimated separation |','| --- | --- | --- |',...pairs.map(p=>`| ${p.a}/${p.b} | ${p.image.time.toFixed(3)} / ${p.image.image.toFixed(3)} | ${p.scene?p.scene.time.toFixed(3)+' / '+p.scene.scene!.toFixed(3):'unavailable'} |`),'','## Events',`${data.events.length} geometric event hypotheses; evidence is included in the JSON and event CSV.`,'','## Limitations',...data.warnings.map(w=>'- '+w),'- Identity switches are unknown without labeled ground truth.','- Manual reference scale is approximate and camera motion can invalidate it.','- Encirclement measures geometry, not biological behavior.'].join('\n');download(new Blob([text],{type:'text/markdown'}),'4DLiveSpace_research_report.md');return;}
  if(kind==='pairs'){const rows=[['time_seconds','frame','subject_a','subject_b','image_distance_normalized','estimated_scene_distance','relative_speed','approaching','quality_index','scene_units']];for(const p of closestPairs(data)){const samples=pairObservations(data,p.a,p.b);samples.forEach((r,i)=>{const prior=samples[i-1],sameCoordinates=prior&&((prior.scene===null)===(r.scene===null)),approaching=prior&&sameCoordinates&&r.time-prior.time<=.65?(r.scene??r.image)<(prior.scene??prior.image):null;rows.push([String(r.time),String(r.frame),String(r.a),String(r.b),String(r.image),r.scene===null?'':String(r.scene),r.relativeSpeed===null?'':String(r.relativeSpeed),approaching===null?'':String(approaching),String(r.quality),data.refinement?.units??'relative scene units']);});}download(new Blob([rows.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'4DLiveSpace_research_pairs.csv');return;}
  if(kind==='report'||kind==='frames'){download(new Blob([JSON.stringify(kind==='report'?{...data,description:'Monocular 4D scene and motion analysis / relative estimated scale',viewer:{range:research.get().range,manualAnnotations:research.get().notes,options:research.get().options}}:data.frames)],{type:'application/json'}),`4DLiveSpace_research_${kind}.json`);return;}
  const rows=kind==='events'?[['time_seconds','heuristic','subject_a','subject_b','confidence_index','evidence','evidence_value','window_seconds'],...data.events.map(e=>[e.time,e.type,e.subjects[0],e.subjects[1],e.confidence,e.evidence?.description??e.label,e.evidence?.value,e.evidence?.windowSeconds])]:[['time_seconds','frame','track_id','class_hypothesis','confidence','x','y','depth','relative_speed','heading_radians','visibility','track_quality','depth_quality','scene_units'],...data.frames.flatMap(frame=>frame.subjects.map(s=>[frame.time,frame.frameIndex,s.id,s.classLabel,s.confidence,s.worldEstimate?.x,s.worldEstimate?.y,s.depthEstimate.value,s.velocity?.speed,s.heading,s.stateFlags.join(';'),data.tracks.find(t=>t.id===s.id)?.quality?.score,s.depthEstimate.confidence,data.refinement?.units??'relative scene units']))];
  download(new Blob([rows.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),`4DLiveSpace_research_${kind}.csv`);
}
export async function exportResearchScreenshot(video:HTMLVideoElement|null,mode:'video'|'3d'|'split'|'snapshot'|'presentation'){
  if(!video?.videoWidth||video.readyState<2)throw new Error('No decoded video frame');
  video.pause();await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));
  const scene=document.querySelector<HTMLCanvasElement>('.research-3d-stage canvas');if(mode!=='video'&&!scene)throw new Error('3D canvas unavailable');
  const output=document.createElement('canvas');output.width=mode==='snapshot'?1920:mode==='split'||mode==='presentation'?1600:1000;output.height=mode==='snapshot'?1100:850;const ctx=output.getContext('2d')!;ctx.fillStyle='#111318';ctx.fillRect(0,0,output.width,output.height);const pane=mode==='split'||mode==='snapshot'||mode==='presentation'?800:1000;
  if(mode!=='3d'){const source=document.createElement('canvas');source.width=video.clientWidth*2;source.height=video.clientHeight*2;const context=source.getContext('2d')!,state=research.get(),p=new MotionProjectionService(source.width,source.height,video.videoWidth,video.videoHeight,state.options.fit);context.drawImage(video,p.rect.x,p.rect.y,p.rect.width,p.rect.height);const layer=document.createElement('canvas');layer.width=source.width;layer.height=source.height;const layerContext=layer.getContext('2d')!;layerContext.scale(2,2);drawResearchOverlay(layerContext,new MotionProjectionService(video.clientWidth,video.clientHeight,video.videoWidth,video.videoHeight,state.options.fit),state.analysis,state.options,video.currentTime,state.selected);context.drawImage(layer,0,0);const placement=new MotionProjectionService(pane,790,source.width,source.height,'contain').rect;ctx.drawImage(source,placement.x,placement.y+40,placement.width,placement.height);}
  if(mode!=='video'&&scene){const placement=new MotionProjectionService(pane,790,scene.width,scene.height,'contain').rect;ctx.drawImage(scene,placement.x+(mode==='split'||mode==='snapshot'||mode==='presentation'?800:0),placement.y+40,placement.width,placement.height);}
  if(mode==='snapshot'){const state=research.get(),data=state.analysis,frame=researchFrameAt(data,video.currentTime),subject=frame?.subjects.find(s=>s.id===state.selected);ctx.font='14px sans-serif';ctx.fillStyle='#c9d1dc';const rows=['SELECTED SUBJECT',`Track ${state.selected??'none'}`,subject?.classLabel??'Unobserved',...(subject?[`Detection ${subject.confidence.toFixed(3)}`,`Depth ${subject.depthEstimate.value?.toFixed(3)??'unavailable'}`,`Depth quality ${subject.depthEstimate.confidence?.toFixed(3)??'unavailable'}`,`Relative speed ${subject.velocity?.speed.toFixed(3)??'unavailable'}`]:[]),data?.refinement?.units??'relative scene units','Monocular estimate','No identity ground truth'];rows.forEach((text,i)=>ctx.fillText(text,1620,65+i*28,280));if(data){ctx.font='13px sans-serif';ctx.fillText('OBSERVED TRACK LANES / T '+video.currentTime.toFixed(3)+' s',20,875);data.tracks.slice(0,10).forEach((track,i)=>{const y=902+i*16;ctx.fillStyle='#c9d1dc';ctx.fillText('#'+track.id,20,y+10);ctx.fillStyle=trackColorForExport(track.id);for(const f of data.frames)if(f.subjects.some(s=>s.id===track.id))ctx.fillRect(70+f.time/data.video.duration*1500,y,1500/(data.settings.fps*data.video.duration),10);});ctx.fillStyle='#fff';ctx.fillRect(70+video.currentTime/data.video.duration*1500,895,2,175);}}
  ctx.fillStyle='#e5e8ef';ctx.font='17px sans-serif';ctx.fillText(`4D LiveSpace / Monocular 4D spatial estimate / T ${video.currentTime.toFixed(3)} s`,18,27);
  const state=research.get(),context=spatialContext(state.analysis,video.currentTime,research.spatial);ctx.font='13px sans-serif';ctx.fillText(`Spatial: ${context.mode==='top'?'2.5D':context.mode} / Selected: #${state.selected??'none'}${state.comparison!==null?' + #'+state.comparison:''} / Depth / scale are estimated unless calibrated.`,18,output.height-18,output.width-36);output.toBlob(blob=>{if(blob)download(blob,`4DLiveSpace_research_${mode}_${video.currentTime.toFixed(3)}s.png`);},'image/png');
}
export async function exportAnnotatedVideo(url:string,data:ResearchAnalysis,options:ResearchOptions,selected:number|null,onProgress:(time:number)=>void,signal:AbortSignal,format:'webm'|'mp4'='webm'){
  if(!('MediaRecorder'in window))throw new Error('Annotated WebM export requires MediaRecorder support');
  const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(value=>MediaRecorder.isTypeSupported(value));if(!mime)throw new Error('No supported WebM recorder');
  const video=document.createElement('video');video.muted=true;video.playsInline=true;video.preload='auto';video.src=url;
  const canvas=document.createElement('canvas');canvas.width=data.video.width;canvas.height=data.video.height;const ctx=canvas.getContext('2d')!,layer=document.createElement('canvas');layer.width=canvas.width;layer.height=canvas.height;
  let frame=0;let stream:MediaStream|null=null;let recorder:MediaRecorder|null=null;
  try{
    await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>finish(new Error('Export decoder timed out')),30000);const abort=()=>finish(new DOMException('Export cancelled','AbortError'));const loaded=()=>finish(),failed=()=>finish(new Error('Export decoder failed'));const finish=(error?:Error)=>{clearTimeout(timer);video.removeEventListener('loadeddata',loaded);video.removeEventListener('error',failed);signal.removeEventListener('abort',abort);if(error)reject(error);else resolve();};video.addEventListener('loadeddata',loaded);video.addEventListener('error',failed);signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort();else video.load();});
    stream=canvas.captureStream(30);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5_000_000});const chunks:BlobPart[]=[];
    await new Promise<void>((resolve,reject)=>{
      let error:Error|undefined;const abort=()=>{error??=new DOMException('Export cancelled','AbortError');video.pause();if(recorder?.state==='recording')recorder.stop();};const ended=()=>recorder?.state==='recording'&&recorder.stop();
      const timer=setTimeout(()=>{error=new Error('Export playback stalled');abort();},(data.video.duration+45)*1000);
      recorder!.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder!.onerror=()=>{error=new Error('Annotated video recorder failed');abort();};
      recorder!.onstop=()=>{clearTimeout(timer);signal.removeEventListener('abort',abort);video.removeEventListener('ended',ended);cancelAnimationFrame(frame);if(error)reject(error);else resolve();};
      signal.addEventListener('abort',abort,{once:true});video.addEventListener('ended',ended,{once:true});recorder!.start(1000);
      const draw=()=>{const p=new MotionProjectionService(canvas.width,canvas.height,video.videoWidth,video.videoHeight,'contain');ctx.drawImage(video,p.rect.x,p.rect.y,p.rect.width,p.rect.height);drawResearchOverlay(layer.getContext('2d')!,p,data,options,video.currentTime,selected);ctx.drawImage(layer,0,0);onProgress(video.currentTime);frame=requestAnimationFrame(draw);};draw();if(signal.aborted)abort();else void video.play().catch(reason=>{error=reason;abort();});
    });
    const blob=new Blob(chunks,{type:mime});
    if(format==='mp4'){try{const response=await fetch('/api/motion/research/export/mp4',{method:'POST',headers:{'Content-Type':'video/webm','x-livespace-client':'desktop'},body:blob,signal});if(!response.ok)throw new Error('Local MP4 conversion unavailable');download(await response.blob(),'4DLiveSpace_research_annotated_silent.mp4');return;}catch(error){if(signal.aborted)throw error;research.set({error:'MP4 conversion unavailable; exported silent WebM instead.'});}}
    download(blob,'4DLiveSpace_research_annotated_silent.webm');
  }finally{cancelAnimationFrame(frame);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(track=>track.stop());video.pause();video.removeAttribute('src');video.load();}
}
