import { useEffect,useRef,useState } from 'react';
import { Expand,RotateCcw } from 'lucide-react';
import { AmbientLight,ArrowHelper,AxesHelper,BoxGeometry,BufferAttribute,BufferGeometry,CanvasTexture,Color,DirectionalLight,GridHelper,Group,LineBasicMaterial,LineSegments,Mesh,MeshStandardMaterial,PerspectiveCamera,Raycaster,RingGeometry,Scene,SphereGeometry,Sprite,SpriteMaterial,Vector2,Vector3,WebGLRenderer } from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { researchFrameAt,trackColor,type ResearchAnalysis,type ResearchSubject } from '../../../../packages/shared/src/research.js';
import { research,useResearch } from './store.js';
import { researchHistories } from './VideoOverlayRenderer2D.js';
type Preset='Perspective'|'Top'|'Side'|'Front';
export function ResearchRenderer3D({video,onFullscreen}:{video:HTMLVideoElement|null;onFullscreen:()=>void}){
  const host=useRef<HTMLDivElement>(null),presetChange=useRef<(preset:Preset)=>void>(()=>undefined);
  const [preset,setPreset]=useState<Preset>('Perspective'),[error,setError]=useState('');
  const {analysis}=useResearch();
  useEffect(()=>{
    if(!host.current)return;const mount=host.current;let renderer:WebGLRenderer;
    try{renderer=new WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{research.scene('image');research.set({error:'WebGL unavailable; using image trajectories.'});return;}
    renderer.setPixelRatio(Math.min(2,devicePixelRatio));renderer.domElement.setAttribute('aria-label','Wildlife 3D research canvas');
    const scene=new Scene();scene.background=new Color('#14191e');
    const camera=new PerspectiveCamera(48,1,.05,120),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=45;
    let centre=new Vector3(0,1,5),extent=12,activePreset:Preset='Perspective';
    const change=(name:Preset)=>{activePreset=name;const offsets:Record<Preset,[number,number,number]>={Perspective:[1, .8,-1.2],Top:[0,1.6,.001],Side:[1.6,.5,0],Front:[0,.3,-1.7]};camera.position.copy(centre).add(new Vector3(...offsets[name]).multiplyScalar(extent));camera.far=Math.max(120,extent*12);camera.updateProjectionMatrix();controls.minDistance=Math.max(.1,extent*.1);controls.maxDistance=extent*6;controls.target.copy(centre);controls.update();};presetChange.current=change;change('Perspective');
    const light=new DirectionalLight('#fff',2.5);light.position.set(3,12,-4);scene.add(light,new AmbientLight('#fff',2));
    const floor=new GridHelper(24,24,'#536b61','#303b42');floor.position.z=7;scene.add(floor,new AxesHelper(2));
    const markerGeometry=new BoxGeometry(.4,.3,.5),markerMaterial=new MeshStandardMaterial({color:'#e1e8ef'}),marker=new Mesh(markerGeometry,markerMaterial);marker.position.set(0,3,0);scene.add(marker);
    const frustumGeometry=new BufferGeometry();const origin=[0,3,0],corners=[[-7,0,12],[7,0,12],[7,7,12],[-7,7,12]],vertices:number[]=[];corners.forEach((corner,i)=>vertices.push(...origin,...corner,...corner,...corners[(i+1)%4]));frustumGeometry.setAttribute('position',new BufferAttribute(new Float32Array(vertices),3));const frustumMaterial=new LineBasicMaterial({color:'#66788d',transparent:true,opacity:.5}),frustum=new LineSegments(frustumGeometry,frustumMaterial);scene.add(frustum);
    const sphere=new SphereGeometry(1,20,12),ringGeometry=new RingGeometry(1,1.025,40),eventMaterial=new MeshStandardMaterial({color:'#efb556',emissive:'#efb556',emissiveIntensity:.4}),eventMarkers=new Map<number,Mesh>();
    const ownedMaterials:MeshStandardMaterial[]=[],ownedArrows:ArrowHelper[]=[],labels:SpriteMaterial[]=[];
    const createProxy=(id:number,opacity=1)=>{const group=new Group(),material=new MeshStandardMaterial({color:trackColor(id),transparent:true,opacity}),body=new Mesh(sphere,material),head=new Mesh(sphere,material),halo=new Mesh(ringGeometry,material),arrow=new ArrowHelper(new Vector3(0,0,1),new Vector3(0,0,0),1,trackColor(id),.2,.12);ownedMaterials.push(material);ownedArrows.push(arrow);const bitmap=document.createElement('canvas');bitmap.width=256;bitmap.height=48;const ctx=bitmap.getContext('2d')!;ctx.fillStyle='rgba(12,15,20,.9)';ctx.fillRect(0,0,256,48);ctx.fillStyle=trackColor(id);ctx.font='24px sans-serif';const name=research.get().analysis?.tracks.find(track=>track.id===id)?.label.split(' /')[0]??'Animal';ctx.fillText(`#${String(id).padStart(2,'0')} ${name==='animal_unknown'?'Animal':name}`,12,32,232);const labelMaterial=new SpriteMaterial({map:new CanvasTexture(bitmap),depthTest:false}),label=new Sprite(labelMaterial);labels.push(labelMaterial);label.scale.set(2,.375,1);body.userData.track=id;head.userData.track=id;halo.rotation.x=-Math.PI/2;group.add(body,head,halo,arrow,label);scene.add(group);return {group,body,head,halo,arrow,material,label};};
    type Proxy=ReturnType<typeof createProxy>;
    const proxies=new Map<number,Proxy>(),ghosts=new Map<number,Proxy[]>(),paths=new Map<number,{line:LineSegments;times:number[]}>();
    let currentData:ResearchAnalysis|null=null,frame=0;
    const clearEvents=()=>{for(const marker of eventMarkers.values())scene.remove(marker);eventMarkers.clear();};
    const clear=()=>{for(const proxy of [...proxies.values(),...[...ghosts.values()].flat()])scene.remove(proxy.group);proxies.clear();ghosts.clear();for(const {line} of paths.values()){scene.remove(line);line.geometry.dispose();(line.material as LineBasicMaterial).dispose();}paths.clear();ownedMaterials.splice(0).forEach(material=>material.dispose());labels.splice(0).forEach(material=>{material.map?.dispose();material.dispose();});ownedArrows.splice(0).forEach(arrow=>{arrow.line.geometry.dispose();(arrow.line.material as LineBasicMaterial).dispose();arrow.cone.geometry.dispose();(arrow.cone.material as MeshStandardMaterial).dispose();});};
    const update=(proxy:Proxy,subject:ResearchSubject|null,opacity:number,ghost=false)=>{const options=research.get().options;proxy.group.visible=!!subject?.worldEstimate&&(subject.depthEstimate.confidence??0)>=.4&&options.volumes;if(!subject?.worldEstimate)return;const {x,y,z}=subject.worldEstimate,{length,width,height}=subject.volume;proxy.group.position.set(x,y,z);proxy.group.rotation.y=subject.heading??0;proxy.body.scale.set(width/2,height*.35,length/2);proxy.head.scale.set(width*.36,height*.23,width*.36);proxy.head.position.set(0,height*.18,length*.4);proxy.label.visible=options.labels3D&&!ghost;proxy.label.position.set(0,height*.65,0);proxy.arrow.visible=subject.heading!==null&&!ghost;proxy.arrow.setLength(Math.max(.5,length*.8),.25,.15);proxy.halo.visible=options.uncertainty&&!ghost;proxy.halo.position.y=-y+.02;proxy.halo.scale.set(length*.7+(.8-(subject.depthEstimate.confidence??.15)),length*.7+(.8-(subject.depthEstimate.confidence??.15)),1);proxy.material.opacity=opacity*(options.uncertainty?.4+.6*subject.confidence:1);proxy.material.emissive.set(subject.id===research.get().selected&&!ghost?trackColor(subject.id):'#000');proxy.material.emissiveIntensity=.18;};
    const resize=()=>{if(mount.clientWidth&&mount.clientHeight){renderer.setSize(mount.clientWidth,mount.clientHeight,false);camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();}};
    mount.append(renderer.domElement);const observer=new ResizeObserver(resize);observer.observe(mount);resize();
    const animate=()=>{
      const state=research.get(),data=state.analysis,time=video?.currentTime??0,options=state.options;
      if(data!==currentData)clearEvents();
      if(data!==currentData){clear();currentData=data;if(data){const points=data.frames.flatMap(f=>f.subjects.filter(s=>(s.depthEstimate.confidence??0)>=.4&&s.worldEstimate).map(s=>s.worldEstimate!));if(points.length){const lo=new Vector3(Infinity,0,Infinity),hi=new Vector3(-Infinity,0,-Infinity);for(const p of points){lo.min(new Vector3(p.x,0,p.z));hi.max(new Vector3(p.x,p.y,p.z));}centre=lo.clone().add(hi).multiplyScalar(.5);extent=Math.max(2,hi.distanceTo(lo));floor.scale.setScalar(extent/12);floor.position.set(centre.x,0,centre.z);change(activePreset);}}if(data)for(const track of data.tracks){proxies.set(track.id,createProxy(track.id));ghosts.set(track.id,Array.from({length:3},()=>createProxy(track.id,.2)));const history=researchHistories(data).get(track.id)??[],positions:number[]=[],colors:number[]=[],times:number[]=[];for(let i=1;i<history.length;i++){const a=history[i-1],b=history[i],p=a.subject.worldEstimate,q=b.subject.worldEstimate;if(!p||!q||b.time-a.time>.65)continue;positions.push(p.x,p.y,p.z,q.x,q.y,q.z);const c=new Color(trackColor(track.id)).multiplyScalar(.25+.7*b.time/data.video.duration);colors.push(c.r,c.g,c.b,c.r,c.g,c.b);times.push(b.time);}const geometry=new BufferGeometry();geometry.setAttribute('position',new BufferAttribute(new Float32Array(positions),3));geometry.setAttribute('color',new BufferAttribute(new Float32Array(colors),3));const line=new LineSegments(geometry,new LineBasicMaterial({vertexColors:true}));scene.add(line);paths.set(track.id,{line,times});}}
      const sample=researchFrameAt(data,time);floor.visible=options.floor;frustum.visible=options.frustum;marker.visible=options.frustum;
      if(data!==null&&eventMarkers.size!==data.tracks.length){clearEvents();for(const track of data.tracks){const indicator=new Mesh(sphere,eventMaterial);indicator.scale.setScalar(.12);scene.add(indicator);eventMarkers.set(track.id,indicator);}}else if(!data)clearEvents();
      for(const [id,indicator] of eventMarkers){const subject=sample?.subjects.find(subject=>subject.id===id);indicator.visible=options.events&&!!subject?.worldEstimate&&!!data?.events.some(event=>event.subjects.includes(id)&&event.time<=time&&event.time>time-.5);if(subject?.worldEstimate)indicator.position.set(subject.worldEstimate.x,subject.worldEstimate.y+subject.volume.height*.75+.3,subject.worldEstimate.z);}
      for(const [id,proxy] of proxies){update(proxy,sample?.subjects.find(subject=>subject.id===id)??null,1);const list=ghosts.get(id)!;list.forEach((ghost,i)=>{const t=time-(i+1)*options.ghostInterval;update(ghost,options.ghosts3D&&i<options.ghostCount&&t>=0?researchFrameAt(data,t)?.subjects.find(subject=>subject.id===id)??null:null,.22/(1+i*.6),true);});}
      for(const {line,times} of paths.values()){line.visible=options.trails3D;let end=0;while(end<times.length&&(options.composite||times[end]<=time))end++;let start=0;if(!options.composite&&options.history)while(start<end&&times[start]<time-options.history)start++;line.geometry.setDrawRange(start*2,(end-start)*2);}
      renderer.domElement.dataset.time=String(time);renderer.domElement.dataset.subjects=String(sample?.subjects.filter(subject=>subject.worldEstimate&&(subject.depthEstimate.confidence??0)>=.4).length??0);renderer.domElement.dataset.sampleTime=String(sample?.time??'');controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate);
    };frame=requestAnimationFrame(animate);
    const raycaster=new Raycaster(),mouse=new Vector2();const select=(event:MouseEvent)=>{const rect=renderer.domElement.getBoundingClientRect();mouse.set((event.clientX-rect.x)/rect.width*2-1,-(event.clientY-rect.y)/rect.height*2+1);raycaster.setFromCamera(mouse,camera);const visible=[...proxies.values()].filter(proxy=>proxy.group.visible).flatMap(proxy=>[proxy.body,proxy.head]);const hit=raycaster.intersectObjects(visible)[0];if(hit)research.set({selected:Number(hit.object.userData.track)});};renderer.domElement.addEventListener('click',select);
    const lost=(event:Event)=>{event.preventDefault();setError('WebGL context lost');research.scene('image');};renderer.domElement.addEventListener('webglcontextlost',lost);
    return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('click',select);renderer.domElement.removeEventListener('webglcontextlost',lost);clear();clearEvents();eventMaterial.dispose();sphere.dispose();ringGeometry.dispose();floor.geometry.dispose();if(Array.isArray(floor.material))floor.material.forEach(material=>material.dispose());else floor.material.dispose();frustumGeometry.dispose();frustumMaterial.dispose();markerGeometry.dispose();markerMaterial.dispose();scene.traverse(object=>{if(object instanceof AxesHelper){object.geometry.dispose();if(Array.isArray(object.material))object.material.forEach(material=>material.dispose());else object.material.dispose();}});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();};
  },[video]);
  return <section className="research-view"><header><strong>3D Research / Relative Scene</strong><div><select aria-label="Research camera preset" value={preset} onChange={event=>{const next=event.target.value as Preset;setPreset(next);presetChange.current(next);}}>{['Perspective','Top','Side','Front'].map(name=><option key={name}>{name}</option>)}</select><button title="Reset research camera" aria-label="Reset research camera" onClick={()=>{setPreset('Perspective');presetChange.current('Perspective');}}><RotateCcw size={16}/></button><button title="Fullscreen 3D research" aria-label="Fullscreen 3D research" onClick={onFullscreen}><Expand size={16}/></button></div></header><div ref={host} className="research-3d-stage">{error&&<p role="alert">{error}</p>}{!analysis&&<span className="research-empty">No wildlife analysis loaded</span>}</div><div className="research-axis-legend">X scene horizontal / Y vertical / Z estimated depth / T video time / Relative scale</div></section>;
}
