import { useEffect,useMemo,useRef,useState } from 'react';
import uPlot from 'uplot';
import 'uplot/dist/uPlot.min.css';
import { pairDistance,researchFrameAt,trackColor } from '../../../../packages/shared/src/research.js';
import { research,useResearch } from './store.js';
type Tab='Subjects'|'Events'|'Metrics'|'Depth'|'Diagnostics';
export function ResearchDataPanel({time,video}:{time:number;video:HTMLVideoElement|null}){
  const {analysis,selected,view,job,runtime}=useResearch(),[tab,setTab]=useState<Tab>('Subjects'),[page,setPage]=useState(0),[expanded,setExpanded]=useState(view==='data');
  const host=useRef<HTMLDivElement>(null),plot=useRef<uPlot|null>(null);
  useEffect(()=>{if(view==='data')setExpanded(true);},[view]);
  const chartData=useMemo(():uPlot.AlignedData=>{const frames=analysis?.frames??[];return [frames.map(frame=>frame.time),frames.map(frame=>frame.subjects.find(subject=>subject.id===selected)?.confidence??null),frames.map(frame=>{const subject=frame.subjects.find(subject=>subject.id===selected);if(!subject)return null;const distances=frame.subjects.filter(other=>other.id!==selected).map(other=>pairDistance(subject,other).image);return distances.length?Math.min(...distances):null;})];},[analysis,selected]);
  useEffect(()=>{if(!expanded||!host.current||!chartData[0].length)return;const mount=host.current,chart=new uPlot({width:Math.max(240,mount.clientWidth),height:170,scales:{x:{time:false}},axes:[{stroke:'#aeb8c7',grid:{stroke:'#303840'}},{stroke:'#aeb8c7',grid:{stroke:'#303840'}}],series:[{label:'T (s)'},{label:'Detection score',stroke:'#65c9df',spanGaps:false},{label:'Nearest 2D separation',stroke:'#efb556',spanGaps:false}]},chartData,mount);plot.current=chart;const observer=new ResizeObserver(()=>chart.setSize({width:Math.max(240,mount.clientWidth),height:170}));observer.observe(mount);return()=>{observer.disconnect();chart.destroy();plot.current=null;};},[expanded,chartData]);
  useEffect(()=>{if(plot.current)plot.current.setCursor({left:plot.current.valToPos(time,'x'),top:0});},[time]);
  const frame=researchFrameAt(analysis,time),eventPage=Math.min(page,Math.max(0,Math.ceil((analysis?.events.length??0)/30)-1));
  return <details className="research-data" open={expanded} onToggle={event=>setExpanded(event.currentTarget.open)}><summary>Research Data / Subjects / Events / Metrics</summary><div role="tablist" aria-label="Research panels">{(['Subjects','Events','Metrics','Depth','Diagnostics'] as Tab[]).map(name=><button role="tab" key={name} aria-selected={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div><div className="research-table" role="tabpanel" aria-label={tab}>
    {tab==='Subjects'&&<table><thead><tr>{['Track','Class hypothesis','Score','Observations','First / Last (s)','Current State'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{analysis?.tracks.map(track=><tr key={track.id} style={{borderLeft:`3px solid ${trackColor(track.id)}`}}><td><button aria-label={`Select Track ${track.id}`} onClick={()=>research.set({selected:track.id})}>#{String(track.id).padStart(2,'0')}</button></td><td>{track.label}</td><td>{track.classConfidence.toFixed(2)}</td><td>{track.observations}</td><td>{track.firstSeen.toFixed(2)} / {track.lastSeen.toFixed(2)}</td><td>{frame?.subjects.some(subject=>subject.id===track.id)?'observed':'unobserved'}</td></tr>)}</tbody></table>}
    {tab==='Events'&&<><table><thead><tr><th>T (s)</th><th>Heuristic</th><th>Subjects</th><th>Confidence index</th><th>Interpretation</th></tr></thead><tbody>{analysis?.events.slice(eventPage*30,eventPage*30+30).map(event=><tr key={event.id}><td><button onClick={()=>{if(video){video.pause();video.currentTime=event.time;}}}>{event.time.toFixed(3)}</button></td><td>{event.type}</td><td>{event.subjects.join(', ')}</td><td>{event.confidence.toFixed(2)}</td><td>{event.label}</td></tr>)}</tbody></table><div className="research-options"><button disabled={!eventPage} onClick={()=>setPage(eventPage-1)}>Previous</button><span>Page {eventPage+1}</span><button disabled={(eventPage+1)*30>=(analysis?.events.length??0)} onClick={()=>setPage(eventPage+1)}>Next</button></div></>}
    {tab==='Metrics'&&<table><thead><tr><th>Sample T</th><th>Track</th><th>X</th><th>Y</th><th>Z estimated</th><th>Speed</th><th>Mask quality</th></tr></thead><tbody>{frame?.subjects.map(subject=><tr key={subject.id}><td>{frame.time.toFixed(3)}</td><td>{subject.id}</td><td>{subject.worldEstimate?.x.toFixed(3)??'--'}</td><td>{subject.worldEstimate?.y.toFixed(3)??'--'}</td><td>{subject.worldEstimate?.z.toFixed(3)??'--'}</td><td>{subject.velocity?.speed.toFixed(3)??'--'}</td><td>{subject.maskConfidence?.toFixed(2)??'missing'}</td></tr>)}</tbody></table>}
    {tab==='Depth'&&<dl className="research-metrics"><div><dt>Method</dt><dd>Depth Anything V2 Small / relative inverse depth</dd></div><div><dt>Ground</dt><dd>{analysis?.ground.method??'Unavailable'}</dd></div><div><dt>Scale</dt><dd>Relative scene units / no metric calibration</dd></div><div><dt>Quality</dt><dd>Mask depth spread index, not calibrated probability</dd></div><div><dt>Camera</dt><dd>Assumed pinhole / focal 0.9 image width</dd></div></dl>}
    {tab==='Diagnostics'&&<dl className="research-metrics">{Object.entries({'Runtime':runtime?'Installed / local':'Missing','Status':job?.stage??'Idle','Source T':time.toFixed(3),'Sample T':frame?.time.toFixed(3)??'--','Sample frame':String(frame?.frameIndex??'--'),'Observed subjects':String(frame?.subjects.length??0),'Missing masks':String(frame?.diagnostics.missingMasks??0),'Inference ms / cached':frame?.diagnostics.inferenceMs.toFixed(1)??'--','Sampling FPS':String(analysis?.settings.fps??'--'),'Detector FPS / offline':analysis?`${(analysis.frames.length/Math.max(.001,analysis.runtime.seconds)).toFixed(2)}`:'--','Device':analysis?.runtime.device??'--','Depth availability':frame?'Available / relative':'Unavailable','Interpolation':'Nearest real sample / no invented masks','Cache identity':analysis?.id??'--','Playback inference':'None; cached data only','Warnings':analysis?.warnings.join(' ')??'Analysis not loaded'}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
  </div><div ref={host} className="research-chart"/></details>;
}
