import { useEffect,useMemo,useRef,useState } from 'react';
import uPlot from 'uplot';
import 'uplot/dist/uPlot.min.css';
import { researchFrameAt,trackColor } from '../../../../packages/shared/src/research.js';
import { closestPairs } from '../../../../packages/shared/src/research-metrics.js';
import { research,useResearch } from './store.js';
type Tab='Subjects'|'Events'|'Metrics'|'Pairs'|'Depth'|'Diagnostics';
type Graph='depth'|'speed'|'distance'|'detection';
export function ResearchDataPanel({time,video}:{time:number;video:HTMLVideoElement|null}){
  const {analysis,selected,comparison,view,job,runtime}=useResearch(),[tab,setTab]=useState<Tab>('Subjects'),[page,setPage]=useState(0),[expanded,setExpanded]=useState(view==='data'),[graph,setGraph]=useState<Graph>('depth');
  const host=useRef<HTMLDivElement>(null),plot=useRef<uPlot|null>(null),pairs=useMemo(()=>analysis?closestPairs(analysis):[],[analysis]);
  useEffect(()=>{if(view==='data')setExpanded(true);},[view]);
  const supportedGraphs=useMemo(()=>{const subjects=analysis?.frames.flatMap(f=>f.subjects.filter(s=>s.id===selected))??[],result:Graph[]=[];if(subjects.filter(s=>s.depthEstimate.value!==null).length>=2)result.push('depth');if(subjects.filter(s=>s.velocity).length>=2)result.push('speed');if(subjects.length>=2)result.push('detection');if(comparison!==null&&(analysis?.frames.filter(f=>f.subjects.some(s=>s.id===selected)&&f.subjects.some(s=>s.id===comparison)).length??0)>=2)result.push('distance');return result;},[analysis,selected,comparison]);
  const activeGraph=supportedGraphs.includes(graph)?graph:supportedGraphs[0]??graph;
  const series=useMemo(()=>{const frames=analysis?.frames??[],times:number[]=[],values:Array<number|null>=[];for(let i=0;i<frames.length;i++){const f=frames[i],s=f.subjects.find(s=>s.id===selected),other=f.subjects.find(s=>s.id===comparison);if(i&&f.time-frames[i-1].time>.65){times.push((f.time+frames[i-1].time)/2);values.push(null);}times.push(f.time);values.push(!s?null:activeGraph==='depth'?s.depthEstimate.value:activeGraph==='speed'?s.velocity?.speed??null:activeGraph==='detection'?s.confidence:other?Math.hypot(s.center2D.x-other.center2D.x,s.center2D.y-other.center2D.y):null);}return {data:[times,values] as uPlot.AlignedData,valid:values.filter(v=>v!==null).length};},[analysis,selected,comparison,activeGraph]);
  useEffect(()=>{if(!expanded||!host.current||series.valid<2)return;const mount=host.current,chart=new uPlot({width:Math.max(240,mount.clientWidth),height:180,scales:{x:{time:false}},axes:[{stroke:'#aeb8c7',grid:{stroke:'#303840'}},{stroke:'#aeb8c7',grid:{stroke:'#303840'}}],series:[{label:'T (s)'},{label:activeGraph==='depth'?'Estimated Depth / '+(analysis?.refinement?.units??'relative units'):activeGraph==='speed'?'Relative Speed':activeGraph==='distance'?'Pair distance / normalized image':'Detection score / quality index',stroke:'#65c9df',spanGaps:false}]},series.data,mount);plot.current=chart;const observer=new ResizeObserver(()=>chart.setSize({width:Math.max(240,mount.clientWidth),height:180}));observer.observe(mount);return()=>{observer.disconnect();chart.destroy();plot.current=null;};},[expanded,series,activeGraph,analysis?.refinement?.units]);
  useEffect(()=>{plot.current?.setCursor({left:plot.current.valToPos(time,'x'),top:0});},[time]);
  if(!analysis)return null;
  const frame=researchFrameAt(analysis,time),all=analysis.frames.flatMap(f=>f.subjects),maskCount=all.filter(s=>s.mask.length).length,depthCount=all.filter(s=>s.depthEstimate.value!==null).length,tabs:Tab[]=['Subjects',...(analysis.events.length?['Events' as const]:[]),'Metrics',...(pairs.length?['Pairs' as const]:[]),...(depthCount?['Depth' as const]:[]),'Diagnostics'],eventPage=Math.min(page,Math.max(0,Math.ceil(analysis.events.length/30)-1));
  const activeTab=tabs.includes(tab)?tab:tabs[0];
  const seek=(t:number)=>{if(video){video.pause();video.currentTime=t;}};
  return <details className="research-data" open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Research Data / Subjects / Events / Metrics</summary><div role="tablist" aria-label="Research panels">{tabs.map(name=><button role="tab" key={name} aria-selected={activeTab===name} onClick={()=>setTab(name)}>{name}</button>)}</div><div className="research-table" role="tabpanel" aria-label={activeTab}>
    {activeTab==='Subjects'&&<table><thead><tr>{['Track','Class hypothesis','Track Quality','Continuity','Observations','Observed span (s)'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{analysis.tracks.map(t=><tr key={t.id} style={{borderLeft:'3px solid '+trackColor(t.id)}}><td><button aria-label={'Select Track '+t.id} onClick={()=>research.set({selected:t.id})}>#{String(t.id).padStart(2,'0')}</button></td><td>{t.label}</td><td>{t.quality?Math.round(t.quality.score*100)+'% / index':'Unavailable'}</td><td>{t.quality?Math.round(t.quality.continuity*100)+'%':''}</td><td>{t.observations}</td><td>{t.firstSeen.toFixed(2)} / {t.lastSeen.toFixed(2)}</td></tr>)}</tbody></table>}
    {activeTab==='Events'&&<><table><thead><tr><th>T (s)</th><th>Heuristic</th><th>Subjects</th><th>Quality</th><th>Evidence</th></tr></thead><tbody>{analysis.events.slice(eventPage*30,eventPage*30+30).map(e=><tr key={e.id}><td><button onClick={()=>seek(e.time)}>{e.time.toFixed(3)}</button></td><td>{e.type}</td><td>{e.subjects.join(', ')}</td><td>{e.confidence.toFixed(2)}</td><td>{e.evidence?e.evidence.description+' / '+e.evidence.value.toFixed(3)+' / '+e.evidence.windowSeconds.toFixed(2)+' s':e.label}</td></tr>)}</tbody></table><div className="research-options"><button disabled={!eventPage} onClick={()=>setPage(eventPage-1)}>Previous</button><span>Page {eventPage+1}</span><button disabled={(eventPage+1)*30>=analysis.events.length} onClick={()=>setPage(eventPage+1)}>Next</button></div></>}
    {activeTab==='Pairs'&&<table><thead><tr><th>Pair</th><th>Paired Samples</th><th>Closest image T</th><th>Min 2D</th><th>Closest scene T</th><th>Min estimated scene</th></tr></thead><tbody>{pairs.map(p=><tr key={p.a+':'+p.b}><td><button onClick={()=>{research.set({selected:p.a,comparison:p.b});seek(p.scene?.time??p.image.time);}}>#{p.a} / #{p.b}</button></td><td>{p.observations}</td><td>{p.image.time.toFixed(3)}</td><td>{p.image.image.toFixed(3)}</td><td>{p.scene?.time.toFixed(3)??'Unavailable'}</td><td>{p.scene?.scene?.toFixed(3)??'Unavailable'}</td></tr>)}</tbody></table>}
    {activeTab==='Metrics'&&(frame?.subjects.length?<table><thead><tr><th>Sample T</th><th>Track</th><th>Estimated depth</th><th>Relative Speed</th><th>Depth quality</th></tr></thead><tbody>{frame.subjects.map(s=><tr key={s.id}><td>{frame.time.toFixed(3)}</td><td>{s.id}</td><td>{s.depthEstimate.value?.toFixed(3)??'Unavailable'}</td><td>{s.velocity?.speed.toFixed(3)??'Unavailable'}</td><td>{s.depthEstimate.confidence?.toFixed(2)??'Unavailable'}</td></tr>)}</tbody></table>:<p>No observations at this sampled time.</p>)}
    {activeTab==='Depth'&&<dl className="research-metrics"><div><dt>Method</dt><dd>Depth Anything V2 Small / clip-normalized inverse depth</dd></div><div><dt>Ground</dt><dd>{analysis.ground.method} / not recovered terrain</dd></div><div><dt>Scale</dt><dd>{analysis.refinement?.units??'relative scene units'}</dd></div><div><dt>Smoothing</dt><dd>{analysis.refinement?.smoothing??'off'}</dd></div><div><dt>Camera</dt><dd>Assumed pinhole / focal 0.9 image width</dd></div></dl>}
    {activeTab==='Diagnostics'&&<dl className="research-metrics">{Object.entries({'Runtime':runtime?'Python executable available':'Unavailable','Status':job?.stage??'Idle','Source T':time.toFixed(3),'Sample T':frame?.time.toFixed(3)??'Unavailable','Source Frame':String(Math.round(time*analysis.video.fps)),'Sample frame':String(frame?.frameIndex??'Unavailable'),'Observed subjects':String(frame?.subjects.length??0),'Frames / Tracks / Masks':analysis.frames.length+' / '+analysis.tracks.length+' / '+maskCount,'Depth valid observations':depthCount+' / '+all.length,'Identity switches':'Unknown; no labeled identity ground truth','Missing masks':String(all.length-maskCount),'Sampling FPS':String(analysis.settings.fps),'Processing seconds':analysis.runtime.seconds.toFixed(2),'Device':analysis.runtime.device,'Detector':analysis.models.detector?.id??'Unavailable','Segmenter':analysis.models.segmenter?.id??'Unavailable','Depth model':analysis.models.depth?.id??'Unavailable','Tracker':'Supervision 0.27 ByteTrack / weak-detection recovery','Temporal refinement':analysis.refinement?.version??'Unavailable','Cache identity':analysis.id,'Pipeline version':analysis.pipelineVersion,'Playback inference':'None; cached data only','Warnings':analysis.warnings.join(' ')}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
  </div>{supportedGraphs.length>0&&<label className="research-graph-choice">Graph <select aria-label="Research Graph" value={activeGraph} onChange={e=>setGraph(e.target.value as Graph)}>{supportedGraphs.map(name=><option key={name} value={name}>{{depth:'Estimated Depth',speed:'Relative Speed',distance:'Pair 2D Distance',detection:'Detection Score'}[name]}</option>)}</select></label>}{series.valid>=2&&<div ref={host} className="research-chart" data-valid-points={series.valid}/>}</details>;
}
