import { ChevronFirst,ChevronLast,Pause,Play,SkipBack,SkipForward } from 'lucide-react';
import { trackColor } from '../../../../packages/shared/src/research.js';
import { useMemo } from 'react';
import { closestPairs } from '../../../../packages/shared/src/research-metrics.js';
import { research,useResearch } from './store.js';
export function ResearchTimeline({video,time,playing}:{video:HTMLVideoElement|null;time:number;playing:boolean}){
  const {metadata,analysis,selected}=useResearch(),duration=video&&Number.isFinite(video.duration)?video.duration:metadata?.duration??0;
  const pairs=useMemo(()=>analysis?closestPairs(analysis):[],[analysis]);
  const seek=(target:number)=>{if(video){video.pause();video.currentTime=Math.max(0,Math.min(duration,target));}};
  return <section className="research-timeline" aria-label="Research timeline"><div className="research-event-ticks">{analysis?.events.filter(event=>selected===null||event.subjects.includes(selected)).map(event=><button key={event.id} style={{left:`${event.time/duration*100}%`}} title={`${event.type} / T ${event.time.toFixed(3)} / heuristic ${event.confidence.toFixed(2)}`} aria-label={`Seek event ${event.type} at ${event.time.toFixed(3)}`} onClick={()=>seek(event.time)}><span/></button>)}</div><input aria-label="Research time" type="range" min="0" max={duration} step=".001" value={Math.min(duration,time)} disabled={!duration} onInput={event=>seek(Number(event.currentTarget.value))}/><div className="research-transport">
    <button title="Jump backward 1 second" aria-label="Jump backward 1 second" disabled={!duration} onClick={()=>seek(time-1)}><ChevronFirst size={17}/></button><button title="Previous research frame" aria-label="Previous research frame" disabled={!duration} onClick={()=>seek(time-1/(metadata?.fps??30))}><SkipBack size={17}/></button><button title={playing?'Pause research video':'Play research video'} aria-label={playing?'Pause research video':'Play research video'} disabled={!duration} onClick={()=>{if(playing)video?.pause();else void video?.play().catch(error=>research.set({error:error.message}));}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button title="Next research frame" aria-label="Next research frame" disabled={!duration} onClick={()=>seek(time+1/(metadata?.fps??30))}><SkipForward size={17}/></button><button title="Jump forward 1 second" aria-label="Jump forward 1 second" disabled={!duration} onClick={()=>seek(time+1)}><ChevronLast size={17}/></button><output>{time.toFixed(3)} / {duration.toFixed(3)} s</output><label>Speed <select aria-label="Research playback speed" defaultValue="1" onChange={event=>{if(video)video.playbackRate=Number(event.target.value);}}>{[.25,.5,1,1.5,2].map(speed=><option key={speed} value={speed}>{speed}x</option>)}</select></label><span className="research-muted">Source video is the master clock</span></div>
    <div className="research-frame-readout">Frame {Math.round(Number(video?.dataset.decodedTime??time)*(metadata?.fps??0))} / T {time.toFixed(3)} s / Analysis sample {analysis?analysis.frames.findIndex(f=>Math.abs(f.time-time)<.51/analysis.settings.fps)+1||'unavailable':'unavailable'}</div>
    {analysis?.tracks.length&&<details className="research-visibility" open><summary>Track Visibility / Observed Span</summary><div><strong>VIDEO</strong><div className="research-video-lane"/><small>{duration.toFixed(2)} s</small></div>{analysis.tracks.map(track=><div key={track.id} className={selected===track.id?'selected-lane':''}><button onClick={()=>{research.set({selected:track.id});seek(track.firstSeen);}} style={{color:trackColor(track.id)}}>#{String(track.id).padStart(2,'0')}</button><div>{analysis.frames.flatMap(frame=>frame.subjects.some(subject=>subject.id===track.id)?[<button key={frame.time} aria-label={`Observe Track ${track.id} at ${frame.time.toFixed(3)}`} title={`Observed T ${frame.time.toFixed(3)}`} onClick={()=>{research.set({selected:track.id});seek(frame.time);}} style={{left:`${frame.time/duration*100}%`,width:`${100/(analysis.settings.fps*duration)}%`,background:trackColor(track.id)}}/>]:[])}</div><small>{track.firstSeen.toFixed(2)} - {track.lastSeen.toFixed(2)} s</small></div>)}{analysis.events.length>0&&<div><strong>EVENTS</strong><div>{analysis.events.map(e=><button key={e.id} className="closest-marker" aria-label={`Timeline Event ${e.type} at ${e.time.toFixed(3)}`} title={e.label} style={{left:`${e.time/duration*100}%`}} onClick={()=>{research.set({selected:e.subjects[0],comparison:e.subjects[1]??null});seek(e.time);}}/>)}</div><small>Geometry hypotheses</small></div>}<div><strong>PAIRS</strong><div>{pairs.filter(p=>selected===null||p.a===selected||p.b===selected).map(p=><button key={p.a+':'+p.b} className="closest-marker" aria-label={`Closest Pair ${p.a} and ${p.b}`} title={`Closest ${p.scene?'estimated scene':'image'} approach / #${p.a} #${p.b}`} style={{left:`${(p.scene?.time??p.image.time)/duration*100}%`}} onClick={()=>{research.set({selected:p.a,comparison:p.b});seek(p.scene?.time??p.image.time);}}/>)}</div><small>Closest approach</small></div></details>}
  </section>;
}
