import { useEffect,useRef,useState } from 'react';
import { Activity,Box,Camera,Download,FlaskConical,RefreshCw,Upload,X,MonitorPlay,Minimize } from 'lucide-react';
import { researchAnalysisSchema,researchIdentity } from '../../../../packages/shared/src/research.js';
import type { VideoMetadata } from '../motion/types.js';
import { research,useResearch,type ResearchJob } from './store.js';
import { ResearchVideoView } from './ResearchVideoView.js';
import { ResearchSpatialView } from './ResearchSpatialView.js';
import { ResearchStatus } from './ResearchStatus.js';
import { ResearchCalibration } from './ResearchCalibration.js';
import { ResearchTimeline } from './ResearchTimeline.js';
import { ResearchSettings } from './ResearchSettings.js';
import { ResearchInspector } from './ResearchInspector.js';
import { ResearchDataPanel } from './ResearchDataPanel.js';
import { exportAnnotatedVideo,exportResearchData,exportResearchScreenshot } from './export.js';
import { exportDensity } from './density.js';
import { researchFrameAt } from '../../../../packages/shared/src/research.js';
import { spatialContext } from '../../../../packages/shared/src/research-spatial.js';
import './research.css';
async function jsonRequest(url:string,init?:RequestInit){const response=await fetch(url,init);const json=await response.json().catch(()=>({error:`Local request returned ${response.status}`}));if(!response.ok)throw new Error(json.error??'Local research request failed');return json;}
export function ResearchView(){
  const state=useResearch(),{metadata,analysis,job}=state;
  const [video,setVideo]=useState<HTMLVideoElement|null>(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[importing,setImporting]=useState(false),[recording,setRecording]=useState<number|null>(null),[exportMode,setExportMode]=useState<'report'|'frames'|'tracks'|'events'|'pairs'|'markdown'|'video'|'3d'|'split'|'snapshot'|'annotated'|'presentation'|'heatmap'|'heatmap-csv'|'annotated-mp4'>('report');
  const presentation=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null),exportRun=useRef<AbortController|null>(null),exportProgress=useRef(0);
  const busy=job?.status==='running';
  useEffect(()=>()=>{exportRun.current?.abort();},[]);
  useEffect(()=>{
    let active=true,timer:ReturnType<typeof setTimeout>;const controller=new AbortController();
    const poll=async()=>{try{const key=research.get().key;const info:VideoMetadata=await jsonRequest(key?`/api/motion/research/media/${key}/info`:'/api/motion/demo/info',{signal:controller.signal});if(!active)return;const old=research.get();if(old.metadata?.id!==info.id){video?.pause();if(old.job?.status==='running')void fetch(`/api/motion/research/jobs/${old.job.id}/cancel`,{method:'POST',headers:{'x-livespace-client':'desktop'}});research.set({metadata:info,analysis:null,job:null,selected:null,comparison:null,error:''});}else research.set({metadata:info});if(info.status==='error')research.set({error:info.error??'Video preparation failed'});timer=setTimeout(()=>void poll(),info.status==='preparing'?1000:5000);}catch(error){if(active){research.set({error:error instanceof Error?error.message:'Source unavailable'});timer=setTimeout(()=>void poll(),5000);}}};void poll();void jsonRequest('/api/motion/research/runtime',{signal:controller.signal}).then(data=>{if(active)research.set({runtime:data.available});}).catch(()=>{});return()=>{active=false;controller.abort();clearTimeout(timer);};
  },[state.key,video]);
  useEffect(()=>{
    if(!metadata||metadata.status!=='ready')return;let active=true;const controller=new AbortController();research.set({analysis:null});
    void researchIdentity(metadata.id,state.settings).then(async id=>{const response=await fetch(`/api/motion/research/analyses/${id}`,{signal:controller.signal});if(response.status===404)return;if(!response.ok)throw new Error('Research cache is invalid; use Reanalyze');const data=researchAnalysisSchema.parse(await response.json());if(data.id!==id||data.video.id!==metadata.id)throw new Error('Research cache identity mismatch');if(active){research.load(data);research.set({job:{id,sourceId:metadata.id,status:'complete',stage:'cached',done:data.frames.length,total:data.frames.length,subjects:data.tracks.length,cacheHit:true}});}}).catch(error=>{if(active)research.set({error:error.message});});return()=>{active=false;controller.abort();};
  },[metadata?.id,metadata?.status,state.settings.fps,state.settings.threshold]);
  useEffect(()=>{
    if(!job||job.status!=='running')return;let active=true,timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{const next:ResearchJob=await jsonRequest(`/api/motion/research/jobs/${job.id}`);if(!active)return;if(next.status==='complete'){const data=researchAnalysisSchema.parse(await jsonRequest(`/api/motion/research/analyses/${next.id}`));if(!active)return;if(data.video.id!==research.get().metadata?.id)throw new Error('Analysis source changed before results loaded');research.load(data);}research.set({job:next});if(next.status==='error')research.set({error:next.error??'Local analysis failed'});if(next.status==='running')timer=setTimeout(()=>void poll(),750);}catch(error){if(active)research.set({job:{...job,status:'error',stage:'status unavailable'},error:error instanceof Error?error.message:'Analysis status unavailable'});}};void poll();return()=>{active=false;clearTimeout(timer);};
  },[job?.id,job?.status]);
  useEffect(()=>{if(!video)return;let frame=0,last=0;const tick=(now:number)=>{if(now-last>80){setTime(video.currentTime);setPlaying(!video.paused);last=now;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[video]);
  async function analyze(force=false){if(!metadata)return;try{video?.pause();research.set({error:''});const next:ResearchJob=await jsonRequest('/api/motion/research/jobs',{method:'POST',headers:{'Content-Type':'application/json','x-livespace-client':'desktop'},body:JSON.stringify({sourceId:metadata.id,key:state.key??undefined,settings:state.settings,force})});research.set({job:next});if(next.status==='complete')research.load(researchAnalysisSchema.parse(await jsonRequest(`/api/motion/research/analyses/${next.id}`)));}catch(error){research.set({error:error instanceof Error?error.message:'Local analysis failed'});}}
  async function changeToLocal(selected:File){setImporting(true);try{if(selected.size>256*1024*1024)throw new Error('Local import limit is 256 MB');video?.pause();const result=await jsonRequest('/api/motion/research/media',{method:'POST',headers:{'Content-Type':'application/octet-stream','x-livespace-client':'desktop','x-video-name':encodeURIComponent(selected.name)},body:selected});research.set({key:result.key,metadata:result,analysis:null,job:null,selected:null,comparison:null,error:''});}catch(error){research.set({error:error instanceof Error?error.message:'Local media import failed'});}finally{setImporting(false);}}
  async function refreshSource(key:string|null){try{const info:VideoMetadata=await jsonRequest(key?`/api/motion/research/media/${key}/info`:'/api/motion/demo/info');video?.pause();const changed=info.id!==research.get().metadata?.id;research.set({key,metadata:info,error:'',...(changed?{analysis:null,job:null,selected:null,comparison:null}:{})});}catch(error){research.set({error:error instanceof Error?error.message:'Source unavailable'});}}
  async function capture(){if(!analysis)return;try{if(['report','frames','tracks','events','pairs','markdown'].includes(exportMode))exportResearchData(analysis,exportMode as 'report'|'frames'|'tracks'|'events'|'pairs'|'markdown');else if(exportMode==='heatmap'||exportMode==='heatmap-csv')exportDensity(video?.currentTime??time,exportMode);else if(exportMode==='annotated'||exportMode==='annotated-mp4'){const run=new AbortController();exportRun.current=run;exportProgress.current=0;setRecording(0);await exportAnnotatedVideo(metadata!.url,analysis,state.options,state.selected,t=>{if(t-exportProgress.current>=.2){exportProgress.current=t;setRecording(t);}},run.signal,exportMode==='annotated-mp4'?'mp4':'webm');}else await exportResearchScreenshot(video,exportMode as 'video'|'3d'|'split'|'snapshot'|'presentation');}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))research.set({error:error instanceof Error?error.message:'Export failed'});}finally{setRecording(null);exportRun.current=null;}}
  const fullscreen=()=>{research.set({presentation:true,view:'split'});void presentation.current?.requestFullscreen().catch(error=>research.set({error:error.message}));};
  const context=spatialContext(analysis,time,research.spatial),current=researchFrameAt(analysis,time);
  useEffect(()=>{const changed=()=>{if(!document.fullscreenElement)research.set({presentation:false});};document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[]);
  return <div className={`research-app ${state.presentation?'is-presentation':''}`}><header className="app-header"><a href="/" className="brand"><span className="brand-mark"><FlaskConical size={21}/></span><strong>4D LiveSpace</strong><span className="version-tag">LOCAL</span></a><div className="workspace-name"><FlaskConical size={16}/>4D Research View</div><span className="research-muted">Monocular 4D Scene Analysis</span></header><nav className="mode-bar" aria-label="Workspace modes"><div className="mode-tabs"><a href="/"><Camera size={15}/>Camera</a><a href="/?workspace=cube"><Box size={15}/>4D Cube Lab</a><a href="/motion"><Activity size={15}/>Human Motion Lab</a><a href="/research" className="active" aria-current="page"><FlaskConical size={15}/>4D Research View</a></div></nav><main className="research-main">
    <section className="research-heading"><h1>4D Wildlife Research View</h1><div className="research-options"><button disabled={busy||importing} onClick={()=>void refreshSource(null)}>Root Video</button><button disabled={busy||importing} onClick={()=>file.current?.click()}><Upload size={15}/>Local Media</button><input ref={file} type="file" hidden accept="video/*,.mp4,.mov,.webm,.m4v" onChange={event=>{const selected=event.target.files?.[0];if(selected)void changeToLocal(selected);event.target.value='';}}/><button title="Refresh source video" aria-label="Refresh source video" disabled={busy} onClick={()=>void refreshSource(state.key)}><RefreshCw size={15}/></button></div></section>
    <div className="research-source"><strong>{metadata?.name??'Loading source'}</strong><span>{metadata?.duration.toFixed(2)} s</span><span>{metadata?.width} x {metadata?.height}</span><span>{metadata?.fps.toFixed(2)} FPS</span><span>{metadata?.status}</span><span>{state.key?'Local import / on this PC':'Root media / on this PC'}</span></div>
    {state.error&&<div className="research-error" role="alert">{state.error}<button title="Dismiss research error" aria-label="Dismiss research error" onClick={()=>research.set({error:''})}><X size={15}/></button></div>}
    <div className="research-analysis"><span role="status">{importing?'Importing local video':state.runtime===false?'Research runtime unavailable':state.runtime?'Local inference ready':'Checking runtime'}</span><label>Sample FPS <select aria-label="Research Sample FPS" disabled={busy} value={state.settings.fps} onChange={event=>research.set({settings:{...state.settings,fps:Number(event.target.value) as 2|3|5|10}})}>{[2,3,5,10].map(fps=><option key={fps}>{fps}</option>)}</select></label><label>Detector threshold <input aria-label="Research Detector Threshold" type="number" min=".1" max=".8" step=".01" value={state.settings.threshold} disabled={busy} onChange={event=>research.set({settings:{...state.settings,threshold:Math.max(.1,Math.min(.8,Number(event.target.value)||.23))}})}/></label><button className="primary" disabled={busy||!state.runtime||metadata?.status!=='ready'||importing} onClick={()=>void analyze()}><FlaskConical size={16}/>Analyze Wildlife</button><button disabled={busy||!state.runtime||!metadata||metadata.status!=='ready'} onClick={()=>void analyze(true)}>Reanalyze</button>{busy&&<button onClick={()=>void jsonRequest(`/api/motion/research/jobs/${job!.id}/cancel`,{method:'POST',headers:{'x-livespace-client':'desktop'}}).then(next=>research.set({job:next})).catch(error=>research.set({error:error.message}))}><X size={15}/>Cancel Analysis</button>}<span>{analysis?`${analysis.frames.length} samples / ${analysis.tracks.length} tracks / ${job?.cacheHit?'cache hit':analysis.runtime.device}`:job?.stage??''}</span></div>
    {busy&&<div className="research-progress"><progress value={job.done} max={job.total}/><span>{job.stage} / {job.done} of {job.total} / {job.subjects} observed</span></div>}
    <div className="research-view-controls"><div className="segmented" aria-label="Research views">{(['split','video','3d','data'] as const).map(view=><button key={view} disabled={!analysis?.tracks.length&&view!=='video'&&view!=='split'} aria-pressed={state.view===view} onClick={()=>research.set({view})}>{{split:'Split',video:'Video','3d':'3D Research',data:'Data'}[view]}</button>)}</div><select aria-label="Research Export" value={exportMode} onChange={event=>setExportMode(event.target.value as typeof exportMode)}><option value="report">Combined Report JSON</option><option value="frames">Per-frame JSON</option><option value="tracks">Track CSV</option><option value="events">Event CSV</option><option value="pairs">Pair CSV</option><option value="markdown">Analysis Report Markdown</option><option value="presentation">Presentation PNG</option><option value="heatmap">Heatmap PNG</option><option value="heatmap-csv">Heatmap Raw Bins CSV</option><option value="snapshot">Research Snapshot PNG</option><option value="video">Annotated PNG</option><option value="3d">3D PNG</option><option value="split">Split PNG</option><option value="annotated-mp4">Annotated Video / Local H.264 MP4</option><option value="annotated">Annotated Video / Silent WebM</option></select><button title="Export research data" aria-label="Export research data" disabled={!analysis||recording!==null} onClick={()=>void capture()}><Download size={16}/></button>{recording!==null&&<><span>Recording export / {recording.toFixed(1)} s</span><button aria-label="Cancel annotated export" title="Cancel annotated export" onClick={()=>exportRun.current?.abort()}><X size={16}/></button></>}</div>
    <button className="research-enter-presentation" disabled={!analysis?.tracks.length} onClick={()=>research.set({presentation:true,view:'split'})}><MonitorPlay size={16}/>Presentation Mode</button><ResearchStatus time={time}/><ResearchSettings video={video}/><ResearchCalibration video={video}/><div ref={presentation} className={`research-presentation mode-${state.view}`}><div className="research-presentation-bar"><strong>4D LiveSpace</strong><span>Subjects: {current?.subjects.length??0}</span><span>Selected: #{state.selected??'none'}{state.comparison!==null?` + #${state.comparison}`:''}</span><span>Spatial: {context.mode==='top'?'2.5D':context.mode}</span><span>Depth: {context.mode==='image'?'Unavailable':'Estimated'}</span><span>T: {time.toFixed(2)} s</span><span>Scale: {analysis?.refinement?.units==='approximate metres'?'Approximate':'Relative'}</span><button aria-label="Exit presentation mode" title="Exit presentation mode" onClick={()=>{research.set({presentation:false});if(document.fullscreenElement)void document.exitFullscreen();}}><Minimize size={16}/></button></div><div className="research-views"><ResearchVideoView url={metadata?.status==='ready'?metadata.url:''} video={video} setVideo={setVideo} onFullscreen={fullscreen}/><ResearchSpatialView video={video} time={time} onFullscreen={fullscreen}/></div><ResearchTimeline video={video} time={time} playing={playing}/><ResearchInspector time={time}/></div><ResearchDataPanel time={time} video={video}/>
  </main></div>;
}
