import { useEffect,useRef } from 'react';
import { Expand } from 'lucide-react';
import { researchFrameAt,trackColor,type ResearchAnalysis,type ResearchSubject } from '../../../../packages/shared/src/research.js';
import { spatialAvailability,validSpatial,type SpatialMode } from '../../../../packages/shared/src/research-metrics.js';
import { research,useResearch } from './store.js';
import { ResearchRenderer3D } from './ResearchRenderer3D.js';
import { researchHistories } from './VideoOverlayRenderer2D.js';

const names:Record<SpatialMode,string>={auto:'AUTO',top:'2.5D Top View',perspective:'Perspective / Relative Depth',image:'Image Trajectory Map', '3d':'Estimated 3D'};
function coordinate(subject:ResearchSubject,mode:SpatialMode){if(mode==='top'||mode==='3d')return validSpatial(subject)?{x:subject.worldEstimate!.x,z:subject.worldEstimate!.z}:null;if(mode==='perspective')return subject.depthEstimate.value!==null?{x:subject.center2D.x,z:subject.depthEstimate.value}:null;return {x:subject.center2D.x,z:subject.center2D.y};}
const boundsCache=new WeakMap<ResearchAnalysis,Map<SpatialMode,{x:number;z:number;w:number;h:number}>>();
function bounds(data:ResearchAnalysis,mode:SpatialMode){let cache=boundsCache.get(data);if(!cache){cache=new Map();boundsCache.set(data,cache);}let result=cache.get(mode);if(result)return result;const points=data.frames.flatMap(f=>f.subjects.flatMap(s=>{const p=coordinate(s,mode);return p?[p]:[];}));const minX=mode==='image'?0:Math.min(0,...points.map(p=>p.x)),maxX=mode==='image'?1:Math.max(1,...points.map(p=>p.x)),minZ=mode==='image'?0:Math.min(...points.map(p=>p.z)),maxZ=mode==='image'?1:Math.max(1,...points.map(p=>p.z));result={x:minX-.1,z:minZ-.1,w:Math.max(.5,maxX-minX)+.2,h:Math.max(.5,maxZ-minZ)+.2};cache.set(mode,result);return result;}
export function ResearchSpatialView({video,time,onFullscreen}:{video:HTMLVideoElement|null;time:number;onFullscreen:()=>void}){
  const state=useResearch(),availability=spatialAvailability(researchFrameAt(state.analysis,time),research.spatial);
  return <div className="research-spatial"><div className="research-spatial-toolbar"><label>Spatial View <select aria-label="Spatial View" value={research.spatial} onChange={e=>research.scene(e.target.value as SpatialMode)}>{(Object.keys(names) as SpatialMode[]).map(mode=><option key={mode} value={mode}>{names[mode]}</option>)}</select></label><span>{availability.available?names[availability.mode]:'No current observations'}{availability.fallback?' / quality fallback':''}</span></div>{availability.mode==='3d'&&availability.available?<ResearchRenderer3D video={video} onFullscreen={onFullscreen}/>:<SpatialMap video={video} onFullscreen={onFullscreen}/>}</div>;
}
function SpatialMap({video,onFullscreen}:{video:HTMLVideoElement|null;onFullscreen:()=>void}){
  const canvas=useRef<HTMLCanvasElement>(null),hits=useRef<Array<{id:number;x:number;y:number}>>([]);
  useEffect(()=>{const element=canvas.current;if(!element)return;const ctx=element.getContext('2d')!;let raf=0;
    const draw=()=>{const state=research.get(),data=state.analysis,time=video?.currentTime??0,frame=researchFrameAt(data,time),availability=spatialAvailability(frame,research.spatial),mode=availability.mode,w=element.clientWidth,h=element.clientHeight,ratio=Math.min(2,devicePixelRatio);if(!w||!h){raf=requestAnimationFrame(draw);return;}if(element.width!==Math.round(w*ratio)||element.height!==Math.round(h*ratio)){element.width=Math.round(w*ratio);element.height=Math.round(h*ratio);}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#14191e';ctx.fillRect(0,0,w,h);hits.current=[];
      element.dataset.time=String(time);element.dataset.subjects=String(frame?.subjects.length??0);element.dataset.sampleTime=String(frame?.time??'');element.dataset.spatialMode=mode;element.dataset.available=String(availability.available);
      if(!data||!availability.available){ctx.fillStyle='#cbd4df';ctx.font='14px sans-serif';ctx.fillText('3D reconstruction unavailable for this segment',20,42,w-40);ctx.fillStyle='#aeb8c7';ctx.font='12px sans-serif';ctx.fillText(data?'No currently observed subjects. Original video remains available.':'Analyze the local video to load real observations.',20,65,w-40);raf=requestAnimationFrame(draw);return;}
      const box=bounds(data,mode),project=(p:{x:number;z:number})=>({x:28+(p.x-box.x)/box.w*(w-56),y:mode==='image'?28+(p.z-box.z)/box.h*(h-72):h-44-(p.z-box.z)/box.h*(h-72)});
      ctx.strokeStyle='#354149';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(28,20);ctx.lineTo(28,h-44);ctx.lineTo(w-20,h-44);ctx.stroke();ctx.fillStyle='#9baab8';ctx.font='11px sans-serif';ctx.fillText(mode==='image'?'Image X / Image Y':mode==='perspective'?'Image X / Estimated Depth':'X / Z estimated ground-reference plane',36,18,w-48);
      const entries=data.frames.filter(f=>state.options.composite||f.time<=time),heat=state.options.heatmap??'off';
      if(heat!=='off'){const bins=new Map<string,number>();for(const sample of entries){let subjects=sample.subjects.filter(s=>heat==='selected'?s.id===state.selected:heat==='cats'?s.classLabel.includes('lion'):heat==='canines'?s.classLabel.includes('hyena'):true);if(heat==='interaction')subjects=subjects.filter(s=>sample.subjects.some(other=>other.id!==s.id&&Math.hypot(s.center2D.x-other.center2D.x,s.center2D.y-other.center2D.y)<.15));for(const s of subjects){const p=coordinate(s,mode);if(!p)continue;const ix=Math.max(0,Math.min(31,Math.floor((p.x-box.x)/box.w*32))),iy=Math.max(0,Math.min(31,Math.floor((p.z-box.z)/box.h*32))),key=`${ix}:${iy}`;bins.set(key,(bins.get(key)??0)+1/data.settings.fps);}}const max=Math.max(0,...bins.values());for(const [key,value] of bins){const [x,z]=key.split(':').map(Number),p=project({x:box.x+x/32*box.w,z:box.z+z/32*box.h});ctx.fillStyle=`rgba(239,181,86,${.08+.55*value/Math.max(.001,max)})`;ctx.fillRect(p.x,mode==='image'?p.y:p.y-(h-72)/32,(w-56)/32,(h-72)/32);}element.dataset.heatmapBins=String(bins.size);ctx.fillStyle='#efb556';ctx.fillText(`${bins.size} occupied bins / ${state.options.composite?'full recorded clip':'observed history to T'} / seconds per bin`,36,h-23,w-48);}else element.dataset.heatmapBins='0';
      if(state.options.trails3D)for(const [id,history] of researchHistories(data)){let prior:typeof history[number]|null=null;for(const entry of history){if(!state.options.composite&&entry.time>time)break;if(!state.options.composite&&state.options.history&&entry.time<time-state.options.history){prior=null;continue;}const p=coordinate(entry.subject,mode),a=prior?coordinate(prior.subject,mode):null;if(p&&a&&prior&&entry.time-prior.time<=.65){const from=project(a),to=project(p);ctx.globalAlpha=.15+.45*(state.options.composite?entry.time/data.video.duration:Math.max(0,1-(time-entry.time)/Math.max(2,state.options.history||time)));ctx.strokeStyle=trackColor(id);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();}prior=entry;}ctx.globalAlpha=1;}
      const subject=(s:ResearchSubject,opacity=1,current=true)=>{const p=coordinate(s,mode);if(!p)return;const point=project(p),quality=mode==='image'?s.confidence:Math.min(s.confidence,s.depthEstimate.confidence??.15),radius=Math.min(16,Math.max(6,s.volume.length/box.w*(w-56)*.22));ctx.save();ctx.translate(point.x,point.y);ctx.globalAlpha=opacity*(.35+.65*quality);ctx.strokeStyle=trackColor(s.id);ctx.fillStyle=trackColor(s.id);ctx.lineWidth=s.id===state.selected?3:1.5;if(state.options.uncertainty&&current){ctx.setLineDash([3,4]);ctx.beginPath();ctx.arc(0,0,radius+6+(1-quality)*9,0,2*Math.PI);ctx.stroke();ctx.setLineDash([]);}ctx.rotate(mode==='image'?0:-(s.heading??0));ctx.beginPath();ctx.ellipse(0,0,radius*.65,radius,0,0,2*Math.PI);ctx.fill();if(s.heading!==null&&mode!=='image'){ctx.beginPath();ctx.arc(0,-radius*.8,radius*.4,0,2*Math.PI);ctx.fill();ctx.beginPath();ctx.moveTo(0,-radius);ctx.lineTo(0,-radius-12);ctx.lineTo(-4,-radius-7);ctx.moveTo(0,-radius-12);ctx.lineTo(4,-radius-7);ctx.stroke();}ctx.restore();if(current){hits.current.push({id:s.id,...point});if(!state.options.labels3D)return;ctx.font='12px sans-serif';ctx.fillStyle=trackColor(s.id);ctx.fillText(`#${String(s.id).padStart(2,'0')}`,Math.min(w-32,point.x+radius+5),Math.max(16,point.y+3));}};
      if(state.options.ghosts3D)for(let i=state.options.ghostCount;i>0;i--){const t=time-i*state.options.ghostInterval;if(t<0)continue;for(const s of researchFrameAt(data,t)?.subjects??[])subject(s,.2/i,false);}
      const a=frame!.subjects.find(s=>s.id===state.selected),b=state.comparison!==null?frame!.subjects.find(s=>s.id===state.comparison):a?frame!.subjects.filter(s=>s.id!==a.id).sort((x,y)=>Math.hypot(x.center2D.x-a.center2D.x,x.center2D.y-a.center2D.y)-Math.hypot(y.center2D.x-a.center2D.x,y.center2D.y-a.center2D.y))[0]:undefined;if(a&&b&&state.options.interactions){const p=coordinate(a,mode),q=coordinate(b,mode);if(p&&q){const from=project(p),to=project(q);ctx.strokeStyle='#e2d38c';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);}}
      if(state.options.volumes)for(const s of frame!.subjects)subject(s);ctx.globalAlpha=1;ctx.fillStyle='#c4cdd8';ctx.font='11px sans-serif';ctx.fillText(`T ${time.toFixed(3)} / ${frame!.subjects.length} observed / ${data.refinement?.units??'relative scene units'}`,12,h-8,w-24);raf=requestAnimationFrame(draw);
    };raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf);
  },[video]);
  return <section className="research-view"><header><strong>Spatial Research / Observations</strong><button aria-label="Fullscreen 3D research" title="Fullscreen spatial research" onClick={onFullscreen}><Expand size={16}/></button></header><div className="research-3d-stage"><canvas ref={canvas} aria-label="Spatial research map" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(),x=e.clientX-rect.x,y=e.clientY-rect.y,hit=hits.current.filter(p=>Math.hypot(p.x-x,p.y-y)<28).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(hit)research.set({selected:hit.id});}}/></div><div className="research-axis-legend">Reference-plane diagram / relative depth / motion heading, not facing / no recovered terrain</div></section>;
}
