import { useMemo,useState } from 'react';
import { pairDistance,pairSummary,researchFrameAt,trackColor } from '../../../../packages/shared/src/research.js';
import { research,useResearch } from './store.js';
const number=(value:number|null|undefined)=>value===null||value===undefined?'--':value.toFixed(3);
export function ResearchInspector({time}:{time:number}){
  const {analysis,selected,comparison,metadata}=useResearch(),[start,setStart]=useState(0),[end,setEnd]=useState<number|null>(null),[expanded,setExpanded]=useState(true);
  const duration=metadata?.duration??0,intervalEnd=Math.min(duration,end??duration),intervalStart=Math.min(start,intervalEnd);
  const summary=useMemo(()=>analysis&&selected!==null&&comparison!==null?pairSummary(analysis,selected,comparison,intervalStart,intervalEnd):null,[analysis,selected,comparison,intervalStart,intervalEnd]);
  const frame=researchFrameAt(analysis,time),subject=frame?.subjects.find(subject=>subject.id===selected),other=frame?.subjects.find(subject=>subject.id===comparison),track=analysis?.tracks.find(track=>track.id===selected),separation=subject&&other?pairDistance(subject,other):null;
  const nearestEvent=analysis?.events.filter(event=>selected!==null&&event.subjects.includes(selected)).reduce<(NonNullable<typeof analysis>)['events'][number]|null>((best,event)=>!best||Math.abs(event.time-time)<Math.abs(best.time-time)?event:best,null);
  const relativeSpeed=subject?.velocity&&other?.velocity?Math.hypot(subject.velocity.x-other.velocity.x,subject.velocity.y-other.velocity.y,subject.velocity.z-other.velocity.z):null;
  const relativeHeading=subject?.heading!==null&&subject?.heading!==undefined&&other?.heading!==null&&other?.heading!==undefined?Math.atan2(Math.sin(subject.heading-other.heading),Math.cos(subject.heading-other.heading))*180/Math.PI:null;
  const nearPair=analysis?.events.filter(event=>event.subjects.includes(selected??-1)&&event.subjects.includes(comparison??-1)&&Math.abs(event.time-time)<.6&&(event.type==='approach'||event.type==='retreat')).at(-1);
  return <details className="research-inspector" aria-label="Research subject inspector" open={expanded} onToggle={event=>setExpanded(event.currentTarget.open)}><summary>Subject / Interaction Inspector</summary><div className="research-options"><label>Selected Subject <select aria-label="Selected Research Subject" value={selected??''} onChange={event=>research.set({selected:Number(event.target.value)})}><option value="" disabled>No selection</option>{analysis?.tracks.map(track=><option key={track.id} value={track.id}>#{String(track.id).padStart(2,'0')} / {track.label}</option>)}</select></label><label>Compare With <select aria-label="Compare Research Subject" value={comparison??''} onChange={event=>research.set({comparison:event.target.value?Number(event.target.value):null})}><option value="">None</option>{analysis?.tracks.filter(track=>track.id!==selected).map(track=><option key={track.id} value={track.id}>#{String(track.id).padStart(2,'0')} / {track.label}</option>)}</select></label><span style={{color:selected?trackColor(selected):undefined}}>{track?`Track ${track.id} / ${track.label}`:'Select an observed subject'}</span></div>
    <dl className="research-metrics">{Object.entries({'T / source seconds':time.toFixed(3),'Sample T':number(frame?.time),'Detection score':number(subject?.confidence),'Tracking':'ByteTrack association / uncertainty uncalibrated','Classification score':number(track?.classConfidence),'Mask quality score':number(subject?.maskConfidence),'Depth quality index':number(subject?.depthEstimate.confidence),'Visibility':subject?'Observed':track&&time>=track.firstSeen&&time<=track.lastSeen?'Unobserved / possible occlusion':'Not observed / outside track span','X / relative units':number(subject?.worldEstimate?.x),'Y / relative units':number(subject?.worldEstimate?.y),'Z / estimated units':number(subject?.worldEstimate?.z),'Speed / units per second':number(subject?.velocity?.speed),'Acceleration / units per second squared':number(subject?.acceleration),'Motion heading / degrees':subject?.heading!==null&&subject?.heading!==undefined?number(subject.heading*180/Math.PI):'--','Facing':'Unknown / proxy head is illustrative','Track span / seconds':track?number(track.lastSeen-track.firstSeen):'--','Track age / seconds':track?number(Math.max(0,time-track.firstSeen)):'--'}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
    {comparison!==null&&<div className="research-pair"><h3>Pairwise Separation / Relative Scale</h3><div className="research-options"><label>Interval Start <input type="number" aria-label="Pair Interval Start" min="0" max={intervalEnd} step=".1" value={intervalStart} onChange={event=>setStart(Math.max(0,Number(event.target.value)))}/></label><label>Interval End <input type="number" aria-label="Pair Interval End" min={intervalStart} max={duration} step=".1" value={intervalEnd} onChange={event=>setEnd(Math.min(duration,Math.max(start,Number(event.target.value))))}/></label></div><dl className="research-metrics">{Object.entries({'Current 2D / normalized image':number(separation?.image),'Current 3D / estimated units':number(separation?.scene),'Minimum 2D':number(summary?.min2D),'Mean 2D':number(summary?.mean2D),'Minimum 3D':number(summary?.min3D),'Mean 3D':number(summary?.mean3D),'Closest 2D approach / seconds':number(summary?.closestTime),'Relative speed / units per second':number(relativeSpeed),'Relative motion heading / degrees':number(relativeHeading),'Approach / retreat':nearPair?.type??'No reliable current hypothesis','Paired observations':String(summary?.count??0)}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div>}
    <small>Monocular 4D motion estimate. Relative depth, flat-ground placement, body volumes and events are inferred, not calibrated measurements. Camera motion affects the estimates.</small>{nearestEvent&&<p className="research-muted">Nearest heuristic event: {nearestEvent.type} / T {nearestEvent.time.toFixed(3)} / {nearestEvent.label}</p>}
  </details>;
}
