import { useMemo,useState } from 'react';
import { pairDistance,pairSummary,researchFrameAt,trackColor } from '../../../../packages/shared/src/research.js';
import { depthLevel,groupMetrics,pairObservations,validSpatial,visibilityState } from '../../../../packages/shared/src/research-metrics.js';
import { research,useResearch } from './store.js';
const number=(value:number)=>value.toFixed(3);
export function ResearchInspector({time}:{time:number}){
  const {analysis,selected,comparison,metadata,options,range}=useResearch(),[expanded,setExpanded]=useState(false);
  const duration=metadata?.duration??0,intervalEnd=range?.end??duration,intervalStart=range?.start??0;
  const summary=useMemo(()=>analysis&&selected!==null&&comparison!==null?pairSummary(analysis,selected,comparison,intervalStart,intervalEnd):null,[analysis,selected,comparison,intervalStart,intervalEnd]);
  const rows=useMemo(()=>analysis&&selected!==null&&comparison!==null?pairObservations(analysis,selected,comparison,intervalStart,intervalEnd):[],[analysis,selected,comparison,intervalStart,intervalEnd]);
  const closest=rows.filter(r=>r.scene!==null).reduce<typeof rows[number]|null>((a,b)=>!a||b.scene!<a.scene!?b:a,null);
  if(!analysis?.tracks.length)return null;
  const frame=researchFrameAt(analysis,time),subject=frame?.subjects.find(s=>s.id===selected),other=frame?.subjects.find(s=>s.id===comparison),track=analysis.tracks.find(t=>t.id===selected),group=groupMetrics(frame,selected),units=analysis.refinement?.units??'relative scene units';
  const metrics:Record<string,string>={'T / source seconds':number(time),'Visibility':selected===null?'No selection':visibilityState(analysis,time,selected)};
  if(track){metrics['Class hypothesis']=track.label;metrics['Class score / not probability']=number(track.classConfidence);if(track.quality){metrics['Track Quality / heuristic']=Math.round(track.quality.score*100)+'%';metrics['Observed continuity']=Math.round(track.quality.continuity*100)+'%';metrics['Missing samples in track span']=String(track.quality.missingSamples);metrics['Identity switches']='Unknown / no identity ground truth';}}
  if(subject){metrics['Detection score']=number(subject.confidence);if(subject.maskConfidence!==null)metrics['Mask quality']=number(subject.maskConfidence);if(subject.depthEstimate.confidence!==null)metrics['Spatial Quality / index, not probability']=number(Math.min(subject.confidence,subject.depthEstimate.confidence));metrics['Depth Confidence']=depthLevel(subject.depthEstimate.confidence);if(subject.depthEstimate.value!==null)metrics['Estimated Depth']=number(subject.depthEstimate.value)+' / '+units;if(validSpatial(subject)){metrics['X / '+units]=number(subject.worldEstimate!.x);metrics['Z / '+units]=number(subject.worldEstimate!.z);}if(subject.velocity)metrics['Relative Speed']=number(subject.velocity.speed)+' '+units+'/s';if(options.experimental&&subject.acceleration!==null)metrics['Acceleration / experimental']=number(subject.acceleration);if(subject.heading!==null)metrics['Motion heading / not facing']=number(subject.heading*180/Math.PI)+' degrees';metrics['Facing']='Unknown / proxy front is illustrative';}
  if(track)metrics['Track span / seconds']=number(track.lastSeen-track.firstSeen);
  const separation=subject&&other?pairDistance(subject,other):null,spatial=subject&&other&&validSpatial(subject)&&validSpatial(other),pair:Record<string,string>={};
  if(separation){pair['Current 2D / normalized image']=number(separation.image);if(spatial&&separation.scene!==null)pair['Current estimated scene separation']=number(separation.scene)+' '+units;if(subject?.velocity&&other?.velocity)pair['Relative Speed']=number(Math.hypot(subject.velocity.x-other.velocity.x,subject.velocity.y-other.velocity.y,subject.velocity.z-other.velocity.z));}
  if(subject?.heading!==null&&subject?.heading!==undefined&&other?.heading!==null&&other?.heading!==undefined)pair['Relative motion heading / degrees']=number(Math.abs(Math.atan2(Math.sin(subject.heading-other.heading),Math.cos(subject.heading-other.heading)))*180/Math.PI);
  if(summary){pair['Minimum 2D']=number(summary.min2D);pair['Mean 2D']=number(summary.mean2D);pair['Closest 2D approach / seconds']=number(summary.closestTime);pair['Paired observations']=String(summary.count);}
  if(closest){const values=rows.filter(r=>r.scene!==null);pair['Mean estimated scene separation']=number(values.reduce((sum,r)=>sum+r.scene!,0)/values.length)+' '+units;pair['Minimum estimated scene separation']=number(closest.scene!)+' '+units;pair['Closest scene approach / seconds']=number(closest.time);pair['Pair quality at closest / index']=number(closest.quality);}
  const event=analysis.events.find(e=>e.time<=time&&time-e.time<.5&&e.subjects.includes(selected??-1)&&e.subjects.includes(comparison??-1)&&(e.type==='approach'||e.type==='retreat'));if(event)pair['Closing / separating']=event.type==='approach'?'Approaching / geometric hypothesis':'Separating / geometric hypothesis';
  return <details className="research-inspector" aria-label="Research subject inspector" open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Subject / Interaction Inspector</summary><div className="research-options"><label>Selected Subject <select aria-label="Selected Research Subject" value={selected??''} onChange={e=>research.set({selected:Number(e.target.value)})}><option value="" disabled>No selection</option>{analysis.tracks.map(t=><option key={t.id} value={t.id}>#{String(t.id).padStart(2,'0')} / {t.label}</option>)}</select></label><label>Compare With <select aria-label="Compare Research Subject" value={comparison??''} onChange={e=>research.set({comparison:e.target.value?Number(e.target.value):null})}><option value="">None</option>{analysis.tracks.filter(t=>t.id!==selected).map(t=><option key={t.id} value={t.id}>#{String(t.id).padStart(2,'0')} / {t.label}</option>)}</select></label><span style={{color:selected?trackColor(selected):undefined}}>{track?'Track '+track.id:''}</span></div><Readouts values={metrics}/>
    {comparison!==null&&<div className="research-pair"><h3>Pairwise Separation / {units}</h3><p>Shared interval: {intervalStart.toFixed(2)} - {intervalEnd.toFixed(2)} s</p>{rows.length?<Readouts values={pair}/>:<p>No overlapping observations for this pair in the selected interval.</p>}</div>}
    {group&&<><h3>Spatial Group Metrics / Focal #{selected}</h3><Readouts values={{'Other observed subjects':String(group.count),'Coordinates':group.coordinates,'Group centroid':number(group.center.x)+', '+number(group.center.z),'RMS group spread':number(group.spread),'Nearest Subject':'#'+group.nearest.id+' / '+number(group.nearest.distance),'Farthest Subject':'#'+group.farthest.id+' / '+number(group.farthest.distance),...(options.experimental&&group.encirclement!==null?{'Encirclement Index / experimental':number(group.encirclement),'Angular coverage / degrees':number(group.angularCoverageDegrees),'Interpretation':'Geometric distribution, not behavior'}:{})}}/></>}
    <small>Monocular 4D Scene Analysis. Ground, volumes and depth are estimates; motion and events can include camera movement. Manual scale remains approximate.</small>
  </details>;
}
function Readouts({values}:{values:Record<string,string>}){return <dl className="research-metrics">{Object.entries(values).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}
