import { useEffect,useRef } from 'react';
import { Expand } from 'lucide-react';
import { researchFrameAt,pairDistance,trackColor,type ResearchAnalysis,type ResearchSubject } from '../../../../packages/shared/src/research.js';
import { projectedHeading,spatialBounds,spatialContext,spatialPoint,spatialSegments,type HeatMode,type TrailMode } from '../../../../packages/shared/src/research-spatial.js';
import { densityRange,gaussianDensity,scopedAnalysis,scopedBins,visualQuality } from '../../../../packages/shared/src/research-visual.js';
import { densityTexture } from './density.js';
import { ResearchVisualControls } from './ResearchVisualControls.js';
import type { SpatialMode } from '../../../../packages/shared/src/research-metrics.js';
import { research,useResearch } from './store.js';
import { ResearchRenderer3D } from './ResearchRenderer3D.js';

const names:Record<SpatialMode,string>={auto:'AUTO',top:'2.5D Top View',perspective:'Perspective / Relative Depth',image:'Image Trajectory Map','3d':'Estimated 3D'};
export function ResearchSpatialView({video,time,onFullscreen}:{video:HTMLVideoElement|null;time:number;onFullscreen:()=>void}){
  const state=useResearch(),context=spatialContext(state.analysis,time,research.spatial),trail=state.options.composite?'full':state.options.spatialTrail??'past';
  return <div className="research-spatial"><details className="research-spatial-config"><summary>Spatial Controls</summary><div className="research-spatial-toolbar">
    <label>Spatial View <select aria-label="Spatial View" value={research.spatial} onChange={e=>research.scene(e.target.value as SpatialMode)}>{(Object.keys(names) as SpatialMode[]).map(mode=><option key={mode} value={mode}>{names[mode]}</option>)}</select></label>
    <span>{context.available?names[context.mode]:'No observations'}{context.historyOnly?' / recorded context; current unobserved':''}</span>
    {!!state.analysis?.tracks.length&&<><label>Trajectory <select aria-label="Spatial Trajectory" value={trail} onChange={e=>research.options({spatialTrail:e.target.value as TrailMode,composite:false})}><option value="current">Current Position</option><option value="past">All Observed Past</option><option value="full">Full Recorded Clip</option></select></label>
    {context.mode!=='3d'&&<><label>Heatmap <select aria-label="Activity Heatmap" value={state.options.heatmap??'all'} onChange={e=>research.options({heatmap:e.target.value as HeatMode})}><option value="off">Off</option><option value="selected">Selected Subject Occupancy</option><option value="all">All Subjects Occupancy</option><option value="interaction">Interaction Density / Proximity</option><option value="pair" disabled={state.comparison===null}>Pair Proximity Density</option>{state.analysis.tracks.some(t=>t.label.includes('lion'))&&<option value="cats">Big-cat Hypotheses</option>}{state.analysis.tracks.some(t=>t.label.includes('hyena'))&&<option value="canines">Canine Hypotheses</option>}</select></label>
    <label>Occupancy Scope <select aria-label="Occupancy Scope" value={state.range?'range':state.options.heatmapScope??'clip'} onChange={e=>research.options({heatmapScope:e.target.value as 'clip'|'past'|'recent'|'range'})}><option value="clip">Whole Recorded Clip</option><option value="past">Observed Past to T</option><option value="recent">Recent Window</option><option value="range" disabled={!state.range}>Selected Time Range</option></select></label></>}</>}
  </div>{context.mode!=='3d'&&<ResearchVisualControls/>}</details>{context.mode==='3d'&&context.available&&!context.historyOnly?<ResearchRenderer3D video={video} onFullscreen={onFullscreen}/>:<SpatialMap video={video} time={time} onFullscreen={onFullscreen}/>}</div>;
}
function SpatialMap({video,time,onFullscreen}:{video:HTMLVideoElement|null;time:number;onFullscreen:()=>void}){
  const canvas=useRef<HTMLCanvasElement>(null),hits=useRef<Array<{id:number;x:number;y:number}>>([]);
  useEffect(()=>{
    const element=canvas.current;if(!element)return;const ctx=element.getContext('2d')!;let raf=0;
    let cachedData:ResearchAnalysis|null=null,cachedKey='',cachedBox={x:0,z:0,w:1,h:1},densityBox={x:0,z:0,w:1,h:1},bins=new Map<string,number>(),texture:HTMLCanvasElement|null=null,densityKey='',densityTotal=0,densityMax=0,densityBuilds=0,paths=new Map<number,ReturnType<typeof spatialSegments>>();
    const draw=()=>{
      const state=research.get(),data=state.analysis,time=video?.currentTime??0,context=spatialContext(data,time,research.spatial),frame=context.current,mode=context.mode,options=state.options,w=element.clientWidth,h=element.clientHeight,ratio=Math.min(2,devicePixelRatio);
      if(!w||!h){raf=requestAnimationFrame(draw);return;}
      if(element.width!==Math.round(w*ratio)||element.height!==Math.round(h*ratio)){element.width=Math.round(w*ratio);element.height=Math.round(h*ratio);}
      ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#14191e';ctx.fillRect(0,0,w,h);hits.current=[];
      element.dataset.time=String(time);element.dataset.subjects=String(frame?.subjects.length??0);element.dataset.trackIds=frame?.subjects.map(s=>s.id).join(',')??'';element.dataset.selected=String(state.selected??'');element.dataset.sampleTime=String(frame?.time??'');element.dataset.spatialMode=mode;element.dataset.available=String(context.available);
      if(!data||!context.available){ctx.fillStyle='#cbd4df';ctx.font='14px sans-serif';ctx.fillText('3D reconstruction unavailable for this segment',20,42,w-40);ctx.font='12px sans-serif';ctx.fillText('No tracked observations. Original video remains available.',20,65,w-40);element.dataset.heatmapBins='0';element.dataset.pathSegments='0';raf=requestAnimationFrame(draw);return;}
      const trail=options.composite?'full':options.spatialTrail??'past',heat=options.heatmap??'all',scope=options.heatmapScope??'clip',bucket=Math.floor(time*data.settings.fps+1e-7),range=state.range,window=options.temporalWindow??0,interval=densityRange(data.video.duration,time,scope,window||2,range),pathRange=range??(window?{start:Math.max(0,time-window),end:time}:null),key=[mode,trail,heat,scope,state.selected,state.comparison,bucket,range?.start,range?.end,window,options.viewport,options.densitySmoothing,options.densityOpacity].join(':');
      if(data!==cachedData||key!==cachedKey){const changed=data!==cachedData;cachedData=data;cachedKey=key;
        const scoped=scopedAnalysis(data,pathRange),boundsData=options.viewport==='selected'&&state.selected!==null?{...scoped,frames:scoped.frames.map(f=>({...f,subjects:f.subjects.filter(s=>s.id===state.selected)}))}:options.viewport==='active'&&frame?.subjects.length?{...data,frames:[frame]}:scoped;
        cachedBox=spatialBounds(boundsData.frames.some(f=>f.subjects.some(s=>spatialPoint(s,mode)))?boundsData:data,mode);paths=new Map(data.tracks.map(t=>[t.id,spatialSegments(scoped,t.id,time,mode,trail)]));
        const heatKey=[mode,heat,state.selected,state.comparison,interval.start,interval.end,options.densitySmoothing,options.densityOpacity,data.video.id].join(':');
        if(changed||heatKey!==densityKey){densityKey=heatKey;densityBox=spatialBounds(data,mode);bins=scopedBins(data,mode,heat,state.selected,state.comparison,interval,densityBox);const density=gaussianDensity(bins,{low:.65,medium:1.2,high:2}[options.densitySmoothing??'medium']);texture=densityTexture(density.values,density.max,options.densityOpacity??.5);densityTotal=density.total;densityMax=density.max;densityBuilds++;}
      }
      const box=cachedBox,project=(p:{x:number;z:number})=>({x:32+(p.x-box.x)/box.w*(w-64),y:mode==='image'?32+(p.z-box.z)/box.h*(h-112):h-80-(p.z-box.z)/box.h*(h-112)});
      const text=(value:string,x:number,y:number,color='#b6c2cd')=>{ctx.fillStyle=color;ctx.font='12px sans-serif';ctx.fillText(value,x,y,Math.max(1,w-x-12));};
      const occupied:Array<{x:number;y:number;w:number;h:number}>=(frame?.subjects??[]).flatMap(s=>{const p=spatialPoint(s,mode);if(!p)return [];const q=project(p);return [{x:q.x-20,y:q.y-32,w:40,h:64}];});
      const annotation=(value:string,x:number,y:number,color:string)=>{
        ctx.font='12px sans-serif';const width=Math.min(w-32,ctx.measureText(value).width+10);x=Math.max(16,Math.min(w-width-16,x));
        let chosen=Math.max(48,Math.min(h-92,y));
        for(const offset of [0,-22,22,-44,44,-66,66,-88,88]){const candidate=Math.max(48,Math.min(h-92,y+offset));if(!occupied.some(r=>x<r.x+r.w&&x+width>r.x&&candidate-14<r.y+r.h&&candidate+6>r.y)){chosen=candidate;break;}}
        occupied.push({x:x-4,y:chosen-14,w:width,h:22});ctx.fillStyle='#11171cf0';ctx.fillRect(x-4,chosen-14,width,22);text(value,x,chosen+2,color);
      };
      ctx.lineWidth=1;ctx.strokeStyle='#222c31';for(let i=0;i<=4;i++){const x=32+i*(w-64)/4,y=32+i*(h-112)/4;ctx.beginPath();ctx.moveTo(x,32);ctx.lineTo(x,h-80);ctx.moveTo(32,y);ctx.lineTo(w-32,y);ctx.stroke();}
      text(mode==='image'?'Image X / Image Y / T':mode==='perspective'?'Image X / inferred depth / T':'X scene horizontal / Z estimated depth / T',32,20);
      ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';
      if(texture){const a=project({x:densityBox.x,z:densityBox.z}),b=project({x:densityBox.x+densityBox.w,z:densityBox.z+densityBox.h});ctx.save();ctx.beginPath();ctx.rect(32,32,w-64,h-112);ctx.clip();if(mode==='image')ctx.drawImage(texture,a.x,a.y,b.x-a.x,b.y-a.y);else{ctx.translate(a.x,a.y);ctx.scale(1,-1);ctx.drawImage(texture,0,0,b.x-a.x,a.y-b.y);}ctx.restore();}
      element.dataset.densityBuilds=String(densityBuilds);element.dataset.densityTotal=String(densityTotal);element.dataset.densityMax=String(densityMax);
      element.dataset.heatmapBins=String(bins.size);element.dataset.heatmapScope=range?'range':scope;element.dataset.trailMode=trail;element.dataset.pathSegments=String([...paths.values()].reduce((sum,p)=>sum+p.length,0));
      const focal=frame?.subjects.find(s=>s.id===state.selected),nearby=focal?(frame?.subjects??[]).filter(s=>s.id!==focal.id).sort((a,b)=>(pairDistance(a,focal).scene??pairDistance(a,focal).image)-(pairDistance(b,focal).scene??pairDistance(b,focal).image)).slice(0,2).map(s=>s.id):[],allowed=options.trailFocus==='all'?null:new Set([state.selected,state.comparison,...(options.trailFocus==='nearby'?nearby:[])]);
      let selectedSegments=0,laterSegments=0;
      if(options.trails3D)for(const [id,segments] of paths){if(allowed&&!allowed.has(id))continue;const selected=id===state.selected;ctx.strokeStyle=trackColor(id);ctx.lineWidth=selected?3:1.2;
        for(const segment of segments){const a=project(segment.from),b=project(segment.to);const age=Math.max(0,time-segment.time),recency=Math.exp(-age/3);ctx.lineWidth=selected?1+2.5*recency:.8+recency;ctx.globalAlpha=segment.laterRecorded?.18:selected?.18+.8*recency:.12+.25*recency;ctx.setLineDash(segment.laterRecorded?[5,5]:[]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(selected)selectedSegments++;if(segment.laterRecorded)laterSegments++;}
        ctx.globalAlpha=1;ctx.setLineDash([]);
        if(selected&&segments.length){const start=project(segments[0].from);ctx.beginPath();ctx.arc(start.x,start.y,4,0,Math.PI*2);ctx.stroke();}
      }
      element.dataset.selectedSegments=String(selectedSegments);element.dataset.laterRecordedSegments=String(laterSegments);
      const subject=(s:ResearchSubject,opacity=1,current=true)=>{
        const p=spatialPoint(s,mode);if(!p)return;const point=project(p),selected=s.id===state.selected,qualities=visualQuality(s,mode),quality=qualities.spatial??qualities.detection,radius=selected?13:10;
        let angle=mode==='top'&&s.heading!==null?projectedHeading(s.heading,(w-64)/box.w,(h-112)/box.h):null;
        if(mode!=='top'){const prior=data.frames.filter(f=>f.time<time&&f.time>=time-.6).reverse().find(f=>f.subjects.some(a=>a.id===s.id)),old=prior?.subjects.find(a=>a.id===s.id),q=old?spatialPoint(old,mode):null;if(q){const a=project(q),dx=point.x-a.x,dy=point.y-a.y;if(Math.hypot(dx,dy)>2)angle=Math.atan2(dx,-dy);}}
        ctx.save();ctx.translate(point.x,point.y);ctx.globalAlpha=opacity*(selected?1:.4);ctx.strokeStyle=trackColor(s.id);ctx.fillStyle=trackColor(s.id);ctx.lineWidth=selected?3:1.5;
        if(options.uncertainty&&current){ctx.setLineDash([3,4]);ctx.beginPath();ctx.arc(0,0,radius+6+(1-quality)*16,0,2*Math.PI);ctx.stroke();ctx.setLineDash([]);}
        ctx.rotate(angle??0);ctx.setLineDash(quality<.4||s.stateFlags.includes('partially occluded')?[3,3]:[]);ctx.beginPath();ctx.ellipse(0,0,radius*.65,radius,0,0,Math.PI*2);ctx.globalAlpha*=.35+.65*quality;ctx.fill();ctx.globalAlpha=opacity*(selected?1:.4);ctx.strokeStyle=selected?'#ffffff':trackColor(s.id);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(0,0,2.5,0,Math.PI*2);ctx.fill();
        if(angle!==null&&current&&quality>=.25){ctx.strokeStyle=trackColor(s.id);ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(0,-radius);ctx.lineTo(0,-radius-23);ctx.lineTo(-5,-radius-15);ctx.moveTo(0,-radius-23);ctx.lineTo(5,-radius-15);ctx.stroke();ctx.beginPath();ctx.arc(0,-radius*.75,4,0,Math.PI*2);ctx.fill();}
        ctx.restore();
        if(current){hits.current.push({id:s.id,...point});if(options.labels3D){const label='#'+String(s.id).padStart(2,'0')+(selected?' NOW':'');const width=ctx.measureText(label).width+10,x=point.x+radius+8+width>w-12?Math.max(12,point.x-radius-width-8):point.x+radius+8,y=Math.max(44,Math.min(h-88,point.y));annotation(label,x,y,trackColor(s.id));}}
      };
      if(trail!=='current'&&options.timeMarkers&&state.selected!==null){const history=data.frames.filter(f=>f.subjects.some(s=>s.id===state.selected)&&(!pathRange||f.time>=pathRange.start&&f.time<=pathRange.end)),targets=trail==='full'?[data.video.duration/3,data.video.duration*2/3]:[time-2,time-1];
        const used=new Set<number>();for(const target of targets){const f=history.reduce<typeof history[number]|null>((best,f)=>!best||Math.abs(f.time-target)<Math.abs(best.time-target)?f:best,null);if(!f||target<0||used.has(f.time)||trail!=='full'&&f.time>time||Math.abs(f.time-target)>.55/data.settings.fps)continue;used.add(f.time);const s=f.subjects.find(s=>s.id===state.selected)!,p=spatialPoint(s,mode);if(p){const q=project(p);ctx.strokeStyle=trackColor(s.id);ctx.beginPath();ctx.arc(q.x,q.y,3,0,Math.PI*2);ctx.stroke();annotation('T '+f.time.toFixed(1),q.x+7,q.y-8,trackColor(s.id));}}
      }
      if(options.centroid){const points=(frame?.subjects??[]).flatMap(s=>{const p=spatialPoint(s,mode);return p?[p]:[];});if(points.length>1){const p=project({x:points.reduce((sum,p)=>sum+p.x,0)/points.length,z:points.reduce((sum,p)=>sum+p.z,0)/points.length});ctx.strokeStyle='#dce4ec';ctx.beginPath();ctx.moveTo(p.x-5,p.y);ctx.lineTo(p.x+5,p.y);ctx.moveTo(p.x,p.y-5);ctx.lineTo(p.x,p.y+5);ctx.stroke();annotation('Group centroid',p.x+8,p.y-8,'#dce4ec');}}
      if(trail!=='current'&&options.ghosts3D)for(let i=options.ghostCount;i>0;i--){const t=time-i*options.ghostInterval;if(t>=0&&(!pathRange||t>=pathRange.start&&t<=pathRange.end))for(const s of researchFrameAt(data,t)?.subjects??[])subject(s,.2/i,false);}
      const a=frame?.subjects.find(s=>s.id===state.selected),b=state.comparison!==null?frame?.subjects.find(s=>s.id===state.comparison):a?frame?.subjects.filter(s=>s.id!==a.id).sort((x,y)=>Math.hypot(x.center2D.x-a.center2D.x,x.center2D.y-a.center2D.y)-Math.hypot(y.center2D.x-a.center2D.x,y.center2D.y-a.center2D.y))[0]:undefined;
      if(a&&b&&options.interactions){const p=spatialPoint(a,mode),q=spatialPoint(b,mode);if(p&&q){const trend=data.events.filter(e=>e.time<=time&&e.time>time-1&&e.subjects.includes(a.id)&&e.subjects.includes(b.id)&&(e.type==='approach'||e.type==='retreat')).at(-1),from=project(p),to=project(q);ctx.strokeStyle='#e2d38c';ctx.lineWidth=1;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);annotation('~'+Math.hypot(p.x-q.x,p.z-q.z).toFixed(2)+(mode==='image'?' image':' XZ')+(trend?trend.type==='approach'?' / Closing':' / Separating':''),Math.min(w-110,Math.max(12,(from.x+to.x)/2)),Math.max(40,(from.y+to.y)/2-8),'#e2d38c');}}
      if(trail!=='current'&&state.selected!==null&&state.comparison!==null&&options.interactions){let closest:{distance:number;time:number;x:number;z:number}|null=null;for(const f of data.frames){if(trail!=='full'&&f.time>time)break;if(pathRange&&(f.time<pathRange.start||f.time>pathRange.end))continue;const a=f.subjects.find(s=>s.id===state.selected),b=f.subjects.find(s=>s.id===state.comparison),p=a?spatialPoint(a,mode):null,q=b?spatialPoint(b,mode):null;if(p&&q){const distance=Math.hypot(p.x-q.x,p.z-q.z);if(!closest||distance<closest.distance)closest={distance,time:f.time,x:(p.x+q.x)/2,z:(p.z+q.z)/2};}}if(closest){const p=project(closest);ctx.strokeStyle='#e2d38c';ctx.strokeRect(p.x-4,p.y-4,8,8);annotation('Closest T '+closest.time.toFixed(2),Math.max(12,Math.min(w-120,p.x+9)),Math.max(44,p.y-10),'#e2d38c');}}
      if(options.volumes)for(const s of frame?.subjects??[])subject(s);
      ctx.globalAlpha=1;text('T '+time.toFixed(3)+' / '+(frame?.subjects.length??0)+' current / '+(mode==='image'?'normalized image coordinates':data.refinement?.units??'relative scene units'),12,h-58);
      text(context.historyOnly?'Current subjects unobserved / recorded context retained':trail==='full'?'Solid: observed past / dashed: later recorded, not prediction':trail==='past'?'Observed past trajectory / current position emphasized':'Current observed positions',12,h-38);
      text(heat==='off'?'Occupancy off':(range?'Range':scope==='clip'?'Whole-clip':scope==='recent'?'Recent window':'Past to T')+' / '+bins.size+' raw bins / '+densityTotal.toFixed(1)+' subject-s',12,h-18,'#b4c4cb');
      raf=requestAnimationFrame(draw);
    };raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf);
  },[video]);
  return <section className="research-view"><header><strong>4D Spatial Research View</strong><button aria-label="Fullscreen 3D research" title="Fullscreen spatial research" onClick={onFullscreen}><Expand size={16}/></button></header><div className="research-3d-stage"><canvas ref={canvas} aria-label="Spatial research map" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(),x=e.clientX-rect.x,y=e.clientY-rect.y,hit=hits.current.filter(p=>Math.hypot(p.x-x,p.y-y)<28).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(hit)research.set({selected:hit.id});}}/></div><QualityLegend time={time}/></section>;
}


function QualityLegend({time}:{time:number}){const state=useResearch(),subject=researchFrameAt(state.analysis,time)?.subjects.find(s=>s.id===state.selected),mode=spatialContext(state.analysis,time,research.spatial).mode,q=subject?visualQuality(subject,mode).spatial:null;return <div className="research-quality-legend"><span>Low occupancy <i className="research-density-scale"/> High occupancy</span><span>Q: spatial estimate quality, not probability</span><span>High: tight ring / Low: faded, wide ring</span>{subject&&<><span>Detection: {(subject.confidence*100).toFixed(0)}%</span><span>Depth: {subject.depthEstimate.confidence===null?'Unavailable':(subject.depthEstimate.confidence*100).toFixed(0)+'%'}</span><span>Spatial Q: {q===null?'Unavailable':q.toFixed(2)}</span><span>Tracking association: Unknown</span></>}</div>;}
