import { pairDistance,researchFrameAt,researchIndex,trackColor,type ResearchAnalysis,type ResearchFrame,type ResearchSubject } from '../../../../packages/shared/src/research.js';
import { MotionProjectionService } from '../motion/MotionProjectionService.js';
import { research,type ResearchOptions } from './store.js';
interface Hit {id:number;x:number;y:number;width:number;height:number}
const histories=new WeakMap<ResearchAnalysis,Map<number,Array<{time:number;subject:ResearchSubject}>>>();
export function researchHistories(data:ResearchAnalysis){let result=histories.get(data);if(!result){result=new Map();for(const frame of data.frames)for(const subject of frame.subjects){const list=result.get(subject.id)??[];list.push({time:frame.time,subject});result.set(subject.id,list);}histories.set(data,result);}return result;}
const heatmaps=new WeakMap<ResearchFrame,HTMLCanvasElement>();
export function drawResearchOverlay(ctx:CanvasRenderingContext2D,p:MotionProjectionService,data:ResearchAnalysis|null,options:ResearchOptions,time:number,selected:number|null){
  const hits:Hit[]=[];ctx.clearRect(0,0,p.width,p.height);ctx.save();ctx.beginPath();ctx.rect(0,0,p.width,p.height);ctx.clip();
  const frame=researchFrameAt(data,time);
  if(data&&frame){
    const labelBounds:Array<{x:number;y:number;width:number;height:number}>=[];
    if(options.depthMap){let layer=heatmaps.get(frame);if(!layer){layer=document.createElement('canvas');layer.width=frame.depthMap.width;layer.height=frame.depthMap.height;const context=layer.getContext('2d')!,image=context.createImageData(layer.width,layer.height);frame.depthMap.values.forEach((depth,i)=>{image.data[i*4]=Math.round(depth*240);image.data[i*4+1]=Math.round(180*(1-Math.abs(depth-.5)*2));image.data[i*4+2]=Math.round((1-depth)*240);image.data[i*4+3]=255;});context.putImageData(image,0,0);heatmaps.set(frame,layer);}const [x,y,w,h]=frame.depthMap.rect,anchor=p.project({x,y});ctx.globalAlpha=.25;ctx.drawImage(layer,anchor.x,anchor.y,w*p.rect.width,h*p.rect.height);ctx.globalAlpha=1;}
    const drawSubject=(subject:ResearchSubject,alpha:number,current:boolean)=>{
      const [x,y,w,h]=subject.bbox,anchor=p.project({x,y}),width=w*p.rect.width,height=h*p.rect.height,color=trackColor(subject.id);
      ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=subject.id===selected?2.5:1.5;ctx.setLineDash(subject.confidence<.35?[4,3]:[]);
      if(options.boxes)ctx.strokeRect(anchor.x,anchor.y,width,height);ctx.setLineDash([]);
      if(options.masks&&subject.mask.length){ctx.beginPath();for(const polygon of subject.mask){polygon.forEach(([px,py],index)=>{const point=p.project({x:px,y:py});if(index===0)ctx.moveTo(point.x,point.y);else ctx.lineTo(point.x,point.y);});ctx.closePath();}if(options.maskStyle!=='outline'){ctx.globalAlpha=alpha*.13;ctx.fill('evenodd');ctx.globalAlpha=alpha;}if(options.maskStyle!=='fill')ctx.stroke();}
      const center=p.project(subject.center2D);ctx.beginPath();ctx.arc(center.x,center.y,current?3.5:2,0,Math.PI*2);ctx.fill();
      if(current){hits.push({id:subject.id,x:anchor.x,y:anchor.y,width,height});
        if(options.ids||options.labels||options.confidence){const title=`${options.ids?`#${String(subject.id).padStart(2,'0')} `:''}${options.labels?subject.classLabel:''}${options.confidence?` / score ${subject.confidence.toFixed(2)}`:''}`;ctx.font='11px sans-serif';const boxWidth=Math.min(p.width-16,ctx.measureText(title).width+12),tx=Math.max(8,Math.min(p.width-boxWidth-8,anchor.x));let ty=Math.max(18,Math.min(p.height-44,anchor.y-5));for(let attempt=0;attempt<frame.subjects.length;attempt++){if(!labelBounds.some(box=>tx-4<box.x+box.width&&tx-4+boxWidth>box.x&&ty-13<box.y+box.height&&ty+4>box.y))break;ty=Math.max(18,ty-20);}labelBounds.push({x:tx-4,y:ty-13,width:boxWidth,height:17});ctx.fillStyle='rgba(12,15,20,.88)';ctx.fillRect(tx-4,ty-13,boxWidth,17);ctx.fillStyle=color;ctx.fillText(title,tx,ty,boxWidth-8);}
        if(options.arrows){const past=researchHistories(data).get(subject.id)?.filter(entry=>entry.time<=time-.25).at(-1);if(past&&time-past.time<.8){const prev=p.project(past.subject.center2D),dx=center.x-prev.x,dy=center.y-prev.y,length=Math.hypot(dx,dy);if(length>2){const scale=Math.min(1,32/length),ex=center.x+dx*scale,ey=center.y+dy*scale,angle=Math.atan2(dy,dx);ctx.beginPath();ctx.moveTo(center.x,center.y);ctx.lineTo(ex,ey);ctx.lineTo(ex-6*Math.cos(angle-.5),ey-6*Math.sin(angle-.5));ctx.moveTo(ex,ey);ctx.lineTo(ex-6*Math.cos(angle+.5),ey-6*Math.sin(angle+.5));ctx.stroke();}}}
      }ctx.globalAlpha=1;
    };
    if(options.ghosts2D)for(let i=options.ghostCount;i>0;i--){const ghostTime=time-i*options.ghostInterval;if(ghostTime<0)continue;const ghost=researchFrameAt(data,ghostTime);if(ghost)for(const subject of ghost.subjects)drawSubject(subject,.1+.2/i,false);}
    if(options.trails2D)for(const [id,history] of researchHistories(data)){ctx.strokeStyle=trackColor(id);ctx.lineWidth=1.5;let previous:typeof history[number]|null=null;for(const entry of history){if(!options.composite&&entry.time>time)break;if(!options.composite&&options.history&&entry.time<time-options.history){previous=null;continue;}const point=p.project(entry.subject.center2D);if(previous&&entry.time-previous.time<=.65){const a=p.project(previous.subject.center2D);ctx.globalAlpha=.15+.6*entry.time/Math.max(.1,time);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(point.x,point.y);ctx.stroke();}previous=entry;}ctx.globalAlpha=1;}
    if(options.interactions)for(const subject of frame.subjects.filter(s=>s.id===selected)){const nearest=frame.subjects.filter(other=>research.get().comparison!==null?other.id===research.get().comparison:other.id!==subject.id).sort((a,b)=>pairDistance(subject,a).image-pairDistance(subject,b).image)[0];if(nearest){const a=p.project(subject.center2D),b=p.project(nearest.center2D);ctx.strokeStyle='#bcc5d2';ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}}
    for(const subject of frame.subjects)drawSubject(subject,1,true);
    if(options.events){const active=data.events.filter(event=>event.time<=time&&event.time>time-.5&&(selected===null||event.subjects.includes(selected))).slice(0,3);ctx.font='11px sans-serif';active.forEach((event,i)=>{ctx.fillStyle='rgba(12,15,20,.88)';ctx.fillRect(8,8+i*20,Math.min(285,p.width-16),18);ctx.fillStyle='#efb556';ctx.fillText(`${event.type} / heuristic ${event.confidence.toFixed(2)}`,14,21+i*20,p.width-28);});}
  }
  const calibration=research.calibration;if(calibration&&calibration.sourceId===data?.video.id){ctx.strokeStyle='#e2d38c';ctx.fillStyle='#e2d38c';ctx.font='12px sans-serif';if(calibration.horizon!==null){const a=p.project({x:0,y:calibration.horizon}),b=p.project({x:1,y:calibration.horizon});ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}if(calibration.ground){const [x,y,w,h]=calibration.ground,a=p.project({x,y});ctx.strokeRect(a.x,a.y,w*p.rect.width,h*p.rect.height);}for(const key of ['a','b'] as const){const point=calibration[key];if(point){const q=p.project(point);ctx.beginPath();ctx.arc(q.x,q.y,5,0,2*Math.PI);ctx.stroke();ctx.fillText(key.toUpperCase(),q.x+8,q.y-5);}}}
  ctx.globalAlpha=1;ctx.fillStyle='rgba(12,15,20,.9)';ctx.fillRect(0,p.height-38,p.width,38);ctx.font='11px sans-serif';ctx.fillStyle='#c9d1dc';ctx.fillText(`T ${time.toFixed(3)}s / Sample ${frame?.time.toFixed(3)??'--'} / ${frame?.subjects.length??0} observed`,8,p.height-22,p.width-16);ctx.fillText('Monocular 4D estimate / X horizontal / Y vertical / Z relative depth',8,p.height-7,p.width-16);ctx.restore();
  return {hits,frame,index:data?researchIndex(data.frames,time):0};
}
