import { it,expect } from 'vitest';
import { researchFixture } from '../fixtures/research.js';
import { occupancyBins,spatialBounds,spatialContext,spatialSegments,projectedHeading } from '../../packages/shared/src/research-spatial.js';
it('screen heading preserves rightward X motion and accounts for axis scaling',()=>{expect(projectedHeading(Math.PI/2,10,20)).toBeCloseTo(Math.PI/2);expect(projectedHeading(-Math.PI/2,10,20)).toBeCloseTo(-Math.PI/2);expect(projectedHeading(Math.PI/4,10,20)).toBeCloseTo(Math.atan2(10,20));});
it('past paths are observed-only; full mode labels later recorded observations',async()=>{const data=await researchFixture();const past=spatialSegments(data,1,.4,'top','past'),full=spatialSegments(data,1,.4,'top','full');expect(past).toHaveLength(2);expect(past.every(p=>!p.laterRecorded)).toBe(true);expect(full).toHaveLength(4);expect(full.filter(p=>p.laterRecorded)).toHaveLength(2);expect(spatialSegments(data,1,.4,'top','current')).toEqual([]);expect(past[1].to.x).toBe(data.frames[2].subjects[0].worldEstimate!.x);});
it('clip occupancy is available at zero and integrates actual sampled subject-time',async()=>{const data=await researchFixture(),box=spatialBounds(data,'top');const all=occupancyBins(data,'top','all',1,null,Infinity,box),past=occupancyBins(data,'top','all',1,null,0,box);expect([...all.values()].reduce((a,b)=>a+b,0)).toBeCloseTo(2);expect([...past.values()].reduce((a,b)=>a+b,0)).toBeCloseTo(.4);expect(occupancyBins(data,'top','selected',1,null,Infinity).size).toBeGreaterThan(0);expect(occupancyBins(data,'top','pair',1,null,Infinity).size).toBe(0);});
it('history context survives an unobserved current segment without fabricating current subjects',async()=>{const data=await researchFixture();data.frames[2].subjects=[];const context=spatialContext(data,.4);expect(context.available).toBe(true);expect(context.historyOnly).toBe(true);expect(context.current?.subjects).toEqual([]);expect(spatialSegments(data,1,.8,'top','full')).toHaveLength(3);});
it('mixed-depth scenes keep all visible IDs in an honest image fallback',async()=>{const data=await researchFixture();data.frames[0].subjects[1].worldEstimate=null;data.frames[0].subjects[1].depthEstimate.value=null;expect(spatialContext(data,0).mode).toBe('image');expect(spatialContext(data,0).current?.subjects.map(s=>s.id)).toEqual([1,2]);});
it('long gaps never become a continuous inferred path',async()=>{const data=await researchFixture();data.frames=data.frames.filter(f=>f.time===0||f.time===.8);expect(spatialSegments(data,1,.8,'top','full')).toEqual([]);});
